package com.lh.pos.bff.dom;

public class LOAN {
	public AMORTIZATION AMORTIZATION;
	public CLOSING_INFORMATION CLOSING_INFORMATION;
	public DOCUMENT_SPECIFIC_DATA_SETS DOCUMENT_SPECIFIC_DATA_SETS;
	public HMDA_LOAN HMDA_LOAN;
	public HOUSING_EXPENSES HOUSING_EXPENSES;
	public LOAN_DETAIL LOAN_DETAIL;
	public LOAN_IDENTIFIERS LOAN_IDENTIFIERS;
	public LOAN_PRODUCT LOAN_PRODUCT;
	public ORIGINATION_SYSTEMS ORIGINATION_SYSTEMS;
	public PURCHASE_CREDITS PURCHASE_CREDITS;
	public TERMS_OF_LOAN TERMS_OF_LOAN;
	public int SequenceNumber;
	public String LoanRoleType;
	public String label;
	public String text;
}
