package com.lh.pos.bff.dom;

public class SUBJECT_PROPERTY {
	public ADDRESS ADDRESS;
	public LOCATION_IDENTIFIER LOCATION_IDENTIFIER;
	public PROPERTY_DETAIL PROPERTY_DETAIL;
	public PROPERTY_VALUATIONS PROPERTY_VALUATIONS;
	public SALES_CONTRACTS SALES_CONTRACTS;
}
