//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * Information specific to drafting of automatic/regular payment.
 *
 * <p>Java class for ACH complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ACH">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACH_ABARoutingAndTransitIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="ACHAccountType" type="{http://www.mismo.org/residential/2009/schemas}ACHAccountEnum" minOccurs="0"/>
 *         &lt;element name="ACHAdditionalEscrowAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="ACHAdditionalPrincipalAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="ACHBankAccountIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="ACHBankAccountPurposeType" type="{http://www.mismo.org/residential/2009/schemas}ACHBankAccountPurposeEnum" minOccurs="0"/>
 *         &lt;element name="ACHBankAccountPurposeTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ACHDraftAfterDueDateDayCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="ACHDraftFrequencyType" type="{http://www.mismo.org/residential/2009/schemas}ACHDraftFrequencyEnum" minOccurs="0"/>
 *         &lt;element name="ACHDraftingPartyName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ACHInstitutionTelegraphicAbbreviationName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ACHPendingDraftEffectiveDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="ACHReceiverSubaccountName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ACHType" type="{http://www.mismo.org/residential/2009/schemas}ACHEnum" minOccurs="0"/>
 *         &lt;element name="ACHWireAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}ACH_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACH", propOrder = {
    "achabaRoutingAndTransitIdentifier",
    "achAccountType",
    "achAdditionalEscrowAmount",
    "achAdditionalPrincipalAmount",
    "achBankAccountIdentifier",
    "achBankAccountPurposeType",
    "achBankAccountPurposeTypeOtherDescription",
    "achDraftAfterDueDateDayCount",
    "achDraftFrequencyType",
    "achDraftingPartyName",
    "achInstitutionTelegraphicAbbreviationName",
    "achPendingDraftEffectiveDate",
    "achReceiverSubaccountName",
    "achType",
    "achWireAmount",
    "extension"
})
public class ACH {

    @XmlElementRef(name = "ACH_ABARoutingAndTransitIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> achabaRoutingAndTransitIdentifier;
    @XmlElementRef(name = "ACHAccountType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ACHAccountEnum> achAccountType;
    @XmlElementRef(name = "ACHAdditionalEscrowAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> achAdditionalEscrowAmount;
    @XmlElementRef(name = "ACHAdditionalPrincipalAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> achAdditionalPrincipalAmount;
    @XmlElementRef(name = "ACHBankAccountIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> achBankAccountIdentifier;
    @XmlElementRef(name = "ACHBankAccountPurposeType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ACHBankAccountPurposeEnum> achBankAccountPurposeType;
    @XmlElementRef(name = "ACHBankAccountPurposeTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> achBankAccountPurposeTypeOtherDescription;
    @XmlElementRef(name = "ACHDraftAfterDueDateDayCount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOCount> achDraftAfterDueDateDayCount;
    @XmlElementRef(name = "ACHDraftFrequencyType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ACHDraftFrequencyEnum> achDraftFrequencyType;
    @XmlElementRef(name = "ACHDraftingPartyName", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> achDraftingPartyName;
    @XmlElementRef(name = "ACHInstitutionTelegraphicAbbreviationName", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> achInstitutionTelegraphicAbbreviationName;
    @XmlElementRef(name = "ACHPendingDraftEffectiveDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> achPendingDraftEffectiveDate;
    @XmlElementRef(name = "ACHReceiverSubaccountName", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> achReceiverSubaccountName;
    @XmlElementRef(name = "ACHType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ACHEnum> achType;
    @XmlElementRef(name = "ACHWireAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> achWireAmount;
    @XmlElement(name = "EXTENSION")
    protected ACHEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    /**
     * Gets the value of the achabaRoutingAndTransitIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getACHABARoutingAndTransitIdentifier() {
        return achabaRoutingAndTransitIdentifier;
    }

    /**
     * Sets the value of the achabaRoutingAndTransitIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setACHABARoutingAndTransitIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.achabaRoutingAndTransitIdentifier = value;
    }

    /**
     * Gets the value of the achAccountType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACHAccountEnum }{@code >}
     *
     */
    public JAXBElement<ACHAccountEnum> getACHAccountType() {
        return achAccountType;
    }

    /**
     * Sets the value of the achAccountType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACHAccountEnum }{@code >}
     *
     */
    public void setACHAccountType(JAXBElement<ACHAccountEnum> value) {
        this.achAccountType = value;
    }

    /**
     * Gets the value of the achAdditionalEscrowAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getACHAdditionalEscrowAmount() {
        return achAdditionalEscrowAmount;
    }

    /**
     * Sets the value of the achAdditionalEscrowAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setACHAdditionalEscrowAmount(JAXBElement<MISMOAmount> value) {
        this.achAdditionalEscrowAmount = value;
    }

    /**
     * Gets the value of the achAdditionalPrincipalAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getACHAdditionalPrincipalAmount() {
        return achAdditionalPrincipalAmount;
    }

    /**
     * Sets the value of the achAdditionalPrincipalAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setACHAdditionalPrincipalAmount(JAXBElement<MISMOAmount> value) {
        this.achAdditionalPrincipalAmount = value;
    }

    /**
     * Gets the value of the achBankAccountIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getACHBankAccountIdentifier() {
        return achBankAccountIdentifier;
    }

    /**
     * Sets the value of the achBankAccountIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setACHBankAccountIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.achBankAccountIdentifier = value;
    }

    /**
     * Gets the value of the achBankAccountPurposeType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACHBankAccountPurposeEnum }{@code >}
     *
     */
    public JAXBElement<ACHBankAccountPurposeEnum> getACHBankAccountPurposeType() {
        return achBankAccountPurposeType;
    }

    /**
     * Sets the value of the achBankAccountPurposeType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACHBankAccountPurposeEnum }{@code >}
     *
     */
    public void setACHBankAccountPurposeType(JAXBElement<ACHBankAccountPurposeEnum> value) {
        this.achBankAccountPurposeType = value;
    }

    /**
     * Gets the value of the achBankAccountPurposeTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getACHBankAccountPurposeTypeOtherDescription() {
        return achBankAccountPurposeTypeOtherDescription;
    }

    /**
     * Sets the value of the achBankAccountPurposeTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setACHBankAccountPurposeTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.achBankAccountPurposeTypeOtherDescription = value;
    }

    /**
     * Gets the value of the achDraftAfterDueDateDayCount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public JAXBElement<MISMOCount> getACHDraftAfterDueDateDayCount() {
        return achDraftAfterDueDateDayCount;
    }

    /**
     * Sets the value of the achDraftAfterDueDateDayCount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public void setACHDraftAfterDueDateDayCount(JAXBElement<MISMOCount> value) {
        this.achDraftAfterDueDateDayCount = value;
    }

    /**
     * Gets the value of the achDraftFrequencyType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACHDraftFrequencyEnum }{@code >}
     *
     */
    public JAXBElement<ACHDraftFrequencyEnum> getACHDraftFrequencyType() {
        return achDraftFrequencyType;
    }

    /**
     * Sets the value of the achDraftFrequencyType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACHDraftFrequencyEnum }{@code >}
     *
     */
    public void setACHDraftFrequencyType(JAXBElement<ACHDraftFrequencyEnum> value) {
        this.achDraftFrequencyType = value;
    }

    /**
     * Gets the value of the achDraftingPartyName property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getACHDraftingPartyName() {
        return achDraftingPartyName;
    }

    /**
     * Sets the value of the achDraftingPartyName property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setACHDraftingPartyName(JAXBElement<MISMOString> value) {
        this.achDraftingPartyName = value;
    }

    /**
     * Gets the value of the achInstitutionTelegraphicAbbreviationName property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getACHInstitutionTelegraphicAbbreviationName() {
        return achInstitutionTelegraphicAbbreviationName;
    }

    /**
     * Sets the value of the achInstitutionTelegraphicAbbreviationName property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setACHInstitutionTelegraphicAbbreviationName(JAXBElement<MISMOString> value) {
        this.achInstitutionTelegraphicAbbreviationName = value;
    }

    /**
     * Gets the value of the achPendingDraftEffectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getACHPendingDraftEffectiveDate() {
        return achPendingDraftEffectiveDate;
    }

    /**
     * Sets the value of the achPendingDraftEffectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setACHPendingDraftEffectiveDate(JAXBElement<MISMODate> value) {
        this.achPendingDraftEffectiveDate = value;
    }

    /**
     * Gets the value of the achReceiverSubaccountName property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getACHReceiverSubaccountName() {
        return achReceiverSubaccountName;
    }

    /**
     * Sets the value of the achReceiverSubaccountName property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setACHReceiverSubaccountName(JAXBElement<MISMOString> value) {
        this.achReceiverSubaccountName = value;
    }

    /**
     * Gets the value of the achType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ACHEnum }{@code >}
     *
     */
    public JAXBElement<ACHEnum> getACHType() {
        return achType;
    }

    /**
     * Sets the value of the achType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ACHEnum }{@code >}
     *
     */
    public void setACHType(JAXBElement<ACHEnum> value) {
        this.achType = value;
    }

    /**
     * Gets the value of the achWireAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getACHWireAmount() {
        return achWireAmount;
    }

    /**
     * Sets the value of the achWireAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setACHWireAmount(JAXBElement<MISMOAmount> value) {
        this.achWireAmount = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link ACHEXTENSION }
     *
     */
    public ACHEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link ACHEXTENSION }
     *
     */
    public void setEXTENSION(ACHEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
