//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for CREDIT_REQUEST complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CREDIT_REQUEST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CREDIT_INQUIRIES" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_INQUIRIES" minOccurs="0"/>
 *         &lt;element name="CREDIT_LIABILITIES" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_LIABILITIES" minOccurs="0"/>
 *         &lt;element name="CREDIT_PUBLIC_RECORDS" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_PUBLIC_RECORDS" minOccurs="0"/>
 *         &lt;element name="CREDIT_REQUEST_DATA_INFORMATION" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_REQUEST_DATA_INFORMATION" minOccurs="0"/>
 *         &lt;element name="CREDIT_REQUEST_DATAS" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_REQUEST_DATAS" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}CREDIT_REQUEST_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CREDIT_REQUEST", propOrder = {
    "creditinquiries",
    "creditliabilities",
    "creditpublicrecords",
    "creditrequestdatainformation",
    "creditrequestdatas",
    "extension"
})
public class CREDITREQUEST {

    @XmlElement(name = "CREDIT_INQUIRIES")
    protected CREDITINQUIRIES creditinquiries;
    @XmlElement(name = "CREDIT_LIABILITIES")
    protected CREDITLIABILITIES creditliabilities;
    @XmlElement(name = "CREDIT_PUBLIC_RECORDS")
    protected CREDITPUBLICRECORDS creditpublicrecords;
    @XmlElement(name = "CREDIT_REQUEST_DATA_INFORMATION")
    protected CREDITREQUESTDATAINFORMATION creditrequestdatainformation;
    @XmlElement(name = "CREDIT_REQUEST_DATAS")
    protected CREDITREQUESTDATAS creditrequestdatas;
    @XmlElement(name = "EXTENSION")
    protected CREDITREQUESTEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the creditinquiries property.
     *
     * @return
     *     possible object is
     *     {@link CREDITINQUIRIES }
     *
     */
    public CREDITINQUIRIES getCREDITINQUIRIES() {
        return creditinquiries;
    }

    /**
     * Sets the value of the creditinquiries property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITINQUIRIES }
     *
     */
    public void setCREDITINQUIRIES(CREDITINQUIRIES value) {
        this.creditinquiries = value;
    }

    /**
     * Gets the value of the creditliabilities property.
     *
     * @return
     *     possible object is
     *     {@link CREDITLIABILITIES }
     *
     */
    public CREDITLIABILITIES getCREDITLIABILITIES() {
        return creditliabilities;
    }

    /**
     * Sets the value of the creditliabilities property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITLIABILITIES }
     *
     */
    public void setCREDITLIABILITIES(CREDITLIABILITIES value) {
        this.creditliabilities = value;
    }

    /**
     * Gets the value of the creditpublicrecords property.
     *
     * @return
     *     possible object is
     *     {@link CREDITPUBLICRECORDS }
     *
     */
    public CREDITPUBLICRECORDS getCREDITPUBLICRECORDS() {
        return creditpublicrecords;
    }

    /**
     * Sets the value of the creditpublicrecords property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITPUBLICRECORDS }
     *
     */
    public void setCREDITPUBLICRECORDS(CREDITPUBLICRECORDS value) {
        this.creditpublicrecords = value;
    }

    /**
     * Gets the value of the creditrequestdatainformation property.
     *
     * @return
     *     possible object is
     *     {@link CREDITREQUESTDATAINFORMATION }
     *
     */
    public CREDITREQUESTDATAINFORMATION getCREDITREQUESTDATAINFORMATION() {
        return creditrequestdatainformation;
    }

    /**
     * Sets the value of the creditrequestdatainformation property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITREQUESTDATAINFORMATION }
     *
     */
    public void setCREDITREQUESTDATAINFORMATION(CREDITREQUESTDATAINFORMATION value) {
        this.creditrequestdatainformation = value;
    }

    /**
     * Gets the value of the creditrequestdatas property.
     *
     * @return
     *     possible object is
     *     {@link CREDITREQUESTDATAS }
     *
     */
    public CREDITREQUESTDATAS getCREDITREQUESTDATAS() {
        return creditrequestdatas;
    }

    /**
     * Sets the value of the creditrequestdatas property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITREQUESTDATAS }
     *
     */
    public void setCREDITREQUESTDATAS(CREDITREQUESTDATAS value) {
        this.creditrequestdatas = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link CREDITREQUESTEXTENSION }
     *
     */
    public CREDITREQUESTEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link CREDITREQUESTEXTENSION }
     *
     */
    public void setEXTENSION(CREDITREQUESTEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
