//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryMethodBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeliveryMethodBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="CommercialCarrier"/>
 *     &lt;enumeration value="ElectronicDelivery"/>
 *     &lt;enumeration value="Email"/>
 *     &lt;enumeration value="Facsimile"/>
 *     &lt;enumeration value="InPerson"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Telephone"/>
 *     &lt;enumeration value="TTY"/>
 *     &lt;enumeration value="USPS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "DeliveryMethodBase")
@XmlEnum
public enum DeliveryMethodBase {


    /**
     * A common carrier used to transport documents and or related materials between parties. For example, Federal Express, United Parcel Service, or any carrier outside of the United States Postal Service.
     *
     */
    @XmlEnumValue("CommercialCarrier")
    COMMERCIAL_CARRIER("CommercialCarrier"),

    /**
     * The upload or passing of written information through an online portal, or other electronic medium.
     *
     */
    @XmlEnumValue("ElectronicDelivery")
    ELECTRONIC_DELIVERY("ElectronicDelivery"),

    /**
     * Messages conforming to a standard electronic mail protocol.
     *
     */
    @XmlEnumValue("Email")
    EMAIL("Email"),

    /**
     * An image of a document made by electronic scanning and transmitted as data by telecommunication links.
     *
     */
    @XmlEnumValue("Facsimile")
    FACSIMILE("Facsimile"),

    /**
     * Delivery achieved via a face to face meeting.
     *
     */
    @XmlEnumValue("InPerson")
    IN_PERSON("InPerson"),
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * The passing of verbal information through a telecommunications enabled device. For example land line, cell phone or Skype.
     *
     */
    @XmlEnumValue("Telephone")
    TELEPHONE("Telephone"),

    /**
     * A telecommunications device for the hearing or sight impaired. (originally called a Teletypewriter)
     *
     */
    TTY("TTY"),

    /**
     * The successor to the Post Office Department, created on July 1, 1971, by the Postal Reorganization Act, as an independent establishment of the executive branch.
     *
     */
    USPS("USPS");
    private final String value;

    DeliveryMethodBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeliveryMethodBase fromValue(String v) {
        for (DeliveryMethodBase c: DeliveryMethodBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
