//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for DISCLOSURE_ON_SERVICER complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DISCLOSURE_ON_SERVICER">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServicerDaysOfTheWeekDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ServicerDirectInquiryToDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ServicerHoursOfTheDayDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ServicerInquiryTelephoneValue" type="{http://www.mismo.org/residential/2009/schemas}MISMONumericString" minOccurs="0"/>
 *         &lt;element name="ServicerPaymentAcceptanceEndDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="ServicerPaymentAcceptanceStartDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="ServicingTransferEffectiveDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="TransferOfServicingDisclosureType" type="{http://www.mismo.org/residential/2009/schemas}TransferOfServicingDisclosureEnum" minOccurs="0"/>
 *         &lt;element name="TransferOfServicingDisclosureTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}DISCLOSURE_ON_SERVICER_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DISCLOSURE_ON_SERVICER", propOrder = {
    "servicerDaysOfTheWeekDescription",
    "servicerDirectInquiryToDescription",
    "servicerHoursOfTheDayDescription",
    "servicerInquiryTelephoneValue",
    "servicerPaymentAcceptanceEndDate",
    "servicerPaymentAcceptanceStartDate",
    "servicingTransferEffectiveDate",
    "transferOfServicingDisclosureType",
    "transferOfServicingDisclosureTypeOtherDescription",
    "extension"
})
public class DISCLOSUREONSERVICER {

    @XmlElementRef(name = "ServicerDaysOfTheWeekDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> servicerDaysOfTheWeekDescription;
    @XmlElementRef(name = "ServicerDirectInquiryToDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> servicerDirectInquiryToDescription;
    @XmlElementRef(name = "ServicerHoursOfTheDayDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> servicerHoursOfTheDayDescription;
    @XmlElementRef(name = "ServicerInquiryTelephoneValue", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMONumericString> servicerInquiryTelephoneValue;
    @XmlElementRef(name = "ServicerPaymentAcceptanceEndDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> servicerPaymentAcceptanceEndDate;
    @XmlElementRef(name = "ServicerPaymentAcceptanceStartDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> servicerPaymentAcceptanceStartDate;
    @XmlElementRef(name = "ServicingTransferEffectiveDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> servicingTransferEffectiveDate;
    @XmlElementRef(name = "TransferOfServicingDisclosureType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<TransferOfServicingDisclosureEnum> transferOfServicingDisclosureType;
    @XmlElementRef(name = "TransferOfServicingDisclosureTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> transferOfServicingDisclosureTypeOtherDescription;
    @XmlElement(name = "EXTENSION")
    protected DISCLOSUREONSERVICEREXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the servicerDaysOfTheWeekDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getServicerDaysOfTheWeekDescription() {
        return servicerDaysOfTheWeekDescription;
    }

    /**
     * Sets the value of the servicerDaysOfTheWeekDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setServicerDaysOfTheWeekDescription(JAXBElement<MISMOString> value) {
        this.servicerDaysOfTheWeekDescription = value;
    }

    /**
     * Gets the value of the servicerDirectInquiryToDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getServicerDirectInquiryToDescription() {
        return servicerDirectInquiryToDescription;
    }

    /**
     * Sets the value of the servicerDirectInquiryToDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setServicerDirectInquiryToDescription(JAXBElement<MISMOString> value) {
        this.servicerDirectInquiryToDescription = value;
    }

    /**
     * Gets the value of the servicerHoursOfTheDayDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getServicerHoursOfTheDayDescription() {
        return servicerHoursOfTheDayDescription;
    }

    /**
     * Sets the value of the servicerHoursOfTheDayDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setServicerHoursOfTheDayDescription(JAXBElement<MISMOString> value) {
        this.servicerHoursOfTheDayDescription = value;
    }

    /**
     * Gets the value of the servicerInquiryTelephoneValue property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMONumericString }{@code >}
     *
     */
    public JAXBElement<MISMONumericString> getServicerInquiryTelephoneValue() {
        return servicerInquiryTelephoneValue;
    }

    /**
     * Sets the value of the servicerInquiryTelephoneValue property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMONumericString }{@code >}
     *
     */
    public void setServicerInquiryTelephoneValue(JAXBElement<MISMONumericString> value) {
        this.servicerInquiryTelephoneValue = value;
    }

    /**
     * Gets the value of the servicerPaymentAcceptanceEndDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getServicerPaymentAcceptanceEndDate() {
        return servicerPaymentAcceptanceEndDate;
    }

    /**
     * Sets the value of the servicerPaymentAcceptanceEndDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setServicerPaymentAcceptanceEndDate(JAXBElement<MISMODate> value) {
        this.servicerPaymentAcceptanceEndDate = value;
    }

    /**
     * Gets the value of the servicerPaymentAcceptanceStartDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getServicerPaymentAcceptanceStartDate() {
        return servicerPaymentAcceptanceStartDate;
    }

    /**
     * Sets the value of the servicerPaymentAcceptanceStartDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setServicerPaymentAcceptanceStartDate(JAXBElement<MISMODate> value) {
        this.servicerPaymentAcceptanceStartDate = value;
    }

    /**
     * Gets the value of the servicingTransferEffectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getServicingTransferEffectiveDate() {
        return servicingTransferEffectiveDate;
    }

    /**
     * Sets the value of the servicingTransferEffectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setServicingTransferEffectiveDate(JAXBElement<MISMODate> value) {
        this.servicingTransferEffectiveDate = value;
    }

    /**
     * Gets the value of the transferOfServicingDisclosureType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TransferOfServicingDisclosureEnum }{@code >}
     *
     */
    public JAXBElement<TransferOfServicingDisclosureEnum> getTransferOfServicingDisclosureType() {
        return transferOfServicingDisclosureType;
    }

    /**
     * Sets the value of the transferOfServicingDisclosureType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TransferOfServicingDisclosureEnum }{@code >}
     *
     */
    public void setTransferOfServicingDisclosureType(JAXBElement<TransferOfServicingDisclosureEnum> value) {
        this.transferOfServicingDisclosureType = value;
    }

    /**
     * Gets the value of the transferOfServicingDisclosureTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getTransferOfServicingDisclosureTypeOtherDescription() {
        return transferOfServicingDisclosureTypeOtherDescription;
    }

    /**
     * Sets the value of the transferOfServicingDisclosureTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setTransferOfServicingDisclosureTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.transferOfServicingDisclosureTypeOtherDescription = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link DISCLOSUREONSERVICEREXTENSION }
     *
     */
    public DISCLOSUREONSERVICEREXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link DISCLOSUREONSERVICEREXTENSION }
     *
     */
    public void setEXTENSION(DISCLOSUREONSERVICEREXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
