//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * Information regarding the location such as latitude and longitude and other location details above and below the surface of earth.
 *
 * <p>Java class for GEOSPATIAL_INFORMATION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GEOSPATIAL_INFORMATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeospatialPropertyIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="LatitudeIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="LongitudeIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="LotBoundaryIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="NaturalLotLocationIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="NaturalUnitSpaceEntryIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}GEOSPATIAL_INFORMATION_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GEOSPATIAL_INFORMATION", propOrder = {
    "geospatialPropertyIdentifier",
    "latitudeIdentifier",
    "longitudeIdentifier",
    "lotBoundaryIdentifier",
    "naturalLotLocationIdentifier",
    "naturalUnitSpaceEntryIdentifier",
    "extension"
})
public class GEOSPATIALINFORMATION {

    @XmlElementRef(name = "GeospatialPropertyIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> geospatialPropertyIdentifier;
    @XmlElementRef(name = "LatitudeIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> latitudeIdentifier;
    @XmlElementRef(name = "LongitudeIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> longitudeIdentifier;
    @XmlElementRef(name = "LotBoundaryIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> lotBoundaryIdentifier;
    @XmlElementRef(name = "NaturalLotLocationIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> naturalLotLocationIdentifier;
    @XmlElementRef(name = "NaturalUnitSpaceEntryIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> naturalUnitSpaceEntryIdentifier;
    @XmlElement(name = "EXTENSION")
    protected GEOSPATIALINFORMATIONEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the geospatialPropertyIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getGeospatialPropertyIdentifier() {
        return geospatialPropertyIdentifier;
    }

    /**
     * Sets the value of the geospatialPropertyIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setGeospatialPropertyIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.geospatialPropertyIdentifier = value;
    }

    /**
     * Gets the value of the latitudeIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getLatitudeIdentifier() {
        return latitudeIdentifier;
    }

    /**
     * Sets the value of the latitudeIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setLatitudeIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.latitudeIdentifier = value;
    }

    /**
     * Gets the value of the longitudeIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getLongitudeIdentifier() {
        return longitudeIdentifier;
    }

    /**
     * Sets the value of the longitudeIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setLongitudeIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.longitudeIdentifier = value;
    }

    /**
     * Gets the value of the lotBoundaryIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getLotBoundaryIdentifier() {
        return lotBoundaryIdentifier;
    }

    /**
     * Sets the value of the lotBoundaryIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setLotBoundaryIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.lotBoundaryIdentifier = value;
    }

    /**
     * Gets the value of the naturalLotLocationIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getNaturalLotLocationIdentifier() {
        return naturalLotLocationIdentifier;
    }

    /**
     * Sets the value of the naturalLotLocationIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setNaturalLotLocationIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.naturalLotLocationIdentifier = value;
    }

    /**
     * Gets the value of the naturalUnitSpaceEntryIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getNaturalUnitSpaceEntryIdentifier() {
        return naturalUnitSpaceEntryIdentifier;
    }

    /**
     * Sets the value of the naturalUnitSpaceEntryIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setNaturalUnitSpaceEntryIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.naturalUnitSpaceEntryIdentifier = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link GEOSPATIALINFORMATIONEXTENSION }
     *
     */
    public GEOSPATIALINFORMATIONEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link GEOSPATIALINFORMATIONEXTENSION }
     *
     */
    public void setEXTENSION(GEOSPATIALINFORMATIONEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
