//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HMDAPreapprovalBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HMDAPreapprovalBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="NotApplicable"/>
 *     &lt;enumeration value="PreapprovalWasNotRequested"/>
 *     &lt;enumeration value="PreapprovalWasRequested"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "HMDAPreapprovalBase")
@XmlEnum
public enum HMDAPreapprovalBase {

    @XmlEnumValue("NotApplicable")
    NOT_APPLICABLE("NotApplicable"),
    @XmlEnumValue("PreapprovalWasNotRequested")
    PREAPPROVAL_WAS_NOT_REQUESTED("PreapprovalWasNotRequested"),
    @XmlEnumValue("PreapprovalWasRequested")
    PREAPPROVAL_WAS_REQUESTED("PreapprovalWasRequested");
    private final String value;

    HMDAPreapprovalBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HMDAPreapprovalBase fromValue(String v) {
        for (HMDAPreapprovalBase c: HMDAPreapprovalBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
