//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * Data specific to the relationship between the seller and the investor, including the reporting and financial obligations between the seller, the servicer, and the investor. The structure also holds data on the investor's interest in the Delivery Loan.
 *
 * <p>Java class for INVESTOR_LOAN_INFORMATION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="INVESTOR_LOAN_INFORMATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseGuarantyFeePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="ConcurrentServicingTransferIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="ExceptionInterestAdjustmentDayMethodType" type="{http://www.mismo.org/residential/2009/schemas}ExceptionInterestAdjustmentDayMethodEnum" minOccurs="0"/>
 *         &lt;element name="ExcessServicingFeeRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="ExecutionType" type="{http://www.mismo.org/residential/2009/schemas}ExecutionEnum" minOccurs="0"/>
 *         &lt;element name="ExecutionTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="FREPrimaryMortgageMarketSurveyPublishedDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="FREPrimaryMortgageMarketSurveyPublishedRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="FREPrimaryMortgageMarketSurveyRoundedRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="FundingInterestAdjustmentDayMethodType" type="{http://www.mismo.org/residential/2009/schemas}FundingInterestAdjustmentDayMethodEnum" minOccurs="0"/>
 *         &lt;element name="GuarantyFeeAddOnIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="GuarantyFeeAfterAlternatePaymentMethodPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="GuarantyFeePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InterestVarianceToleranceMaximumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="InvestorCollateralProgramIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorCommitmentTakeoutPricePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InvestorCreditPolicyEffectiveDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="InvestorDealIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorGroupingIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorGuarantyFeeAfterBuyupBuydownPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InvestorHeldCollateralPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InvestorInstitutionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorLoanCommitmentExpirationDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="InvestorLoanEarlyPayoffPenaltyWaiverIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="InvestorLoanEffectiveDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="InvestorLoanPartialPrepaymentPenaltyWaiverIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="InvestorMasterCommitmentIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorOwnershipPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InvestorOwnershipType" type="{http://www.mismo.org/residential/2009/schemas}InvestorOwnershipEnum" minOccurs="0"/>
 *         &lt;element name="InvestorProductPlanIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorRemittanceDay" type="{http://www.mismo.org/residential/2009/schemas}MISMODay" minOccurs="0"/>
 *         &lt;element name="InvestorRemittanceDaysCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="InvestorRemittanceIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="InvestorRemittanceType" type="{http://www.mismo.org/residential/2009/schemas}InvestorRemittanceEnum" minOccurs="0"/>
 *         &lt;element name="InvestorRemittanceTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="InvestorReportingMethodType" type="{http://www.mismo.org/residential/2009/schemas}InvestorReportingMethodEnum" minOccurs="0"/>
 *         &lt;element name="InvestorRequiredMarginPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="InvestorServicingFeeAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="InvestorServicingFeeRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="LastReportedToInvestorPrincipalBalanceAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LateDeliveryGraceDaysCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="LenderTargetFundingDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="LoanAcquisitionScheduledUPBAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LoanBuyupBuydownBasisPointNumber" type="{http://www.mismo.org/residential/2009/schemas}MISMONumeric" minOccurs="0"/>
 *         &lt;element name="LoanBuyupBuydownType" type="{http://www.mismo.org/residential/2009/schemas}LoanBuyupBuydownEnum" minOccurs="0"/>
 *         &lt;element name="LoanBuyupBuydownTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="LoanDefaultedReportingFrequencyType" type="{http://www.mismo.org/residential/2009/schemas}LoanDefaultedReportingFrequencyEnum" minOccurs="0"/>
 *         &lt;element name="LoanDefaultLossPartyType" type="{http://www.mismo.org/residential/2009/schemas}LoanDefaultLossPartyEnum" minOccurs="0"/>
 *         &lt;element name="LoanDelinquencyAdvanceDaysCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="LoanFundingAdvancedAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LoanPriorOwnerName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="LoanPurchaseDiscountAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LoanPurchasePremiumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LoanServicingFeeBasisPointNumber" type="{http://www.mismo.org/residential/2009/schemas}MISMONumeric" minOccurs="0"/>
 *         &lt;element name="LoanServicingIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="LoanServicingRightsPurchaseOnlyIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="LoanYieldSpreadPremiumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="LoanYieldSpreadPremiumRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="MICoverageServicingFeeRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="NonStandardServicingFeeRetainedByServicerAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="PassThroughCalculationMethodType" type="{http://www.mismo.org/residential/2009/schemas}PassThroughCalculationMethodEnum" minOccurs="0"/>
 *         &lt;element name="PassThroughCeilingRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="PassThroughRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="PrincipalVarianceToleranceMaximumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="RelatedInvestorLoanIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="RelatedLoanInvestorType" type="{http://www.mismo.org/residential/2009/schemas}RelatedLoanInvestorEnum" minOccurs="0"/>
 *         &lt;element name="RelatedLoanInvestorTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="RemoveFromTransferIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="REOMarketingPartyType" type="{http://www.mismo.org/residential/2009/schemas}REOMarketingPartyEnum" minOccurs="0"/>
 *         &lt;element name="REOMarketingPartyTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ServicingFeeMinimumRatePercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="ThirdPartyLoanAcquisitionPriceAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="UPBVarianceToleranceMaximumAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="WarehouseAdvanceAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="WarehouseCommitmentSubcategoryIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="WholeLoanInterestDueAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="WholeLoanPrincipalAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="WholeLoanSaleDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}INVESTOR_LOAN_INFORMATION_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INVESTOR_LOAN_INFORMATION", propOrder = {
    "baseGuarantyFeePercent",
    "concurrentServicingTransferIndicator",
    "exceptionInterestAdjustmentDayMethodType",
    "excessServicingFeeRatePercent",
    "executionType",
    "executionTypeOtherDescription",
    "frePrimaryMortgageMarketSurveyPublishedDate",
    "frePrimaryMortgageMarketSurveyPublishedRatePercent",
    "frePrimaryMortgageMarketSurveyRoundedRatePercent",
    "fundingInterestAdjustmentDayMethodType",
    "guarantyFeeAddOnIndicator",
    "guarantyFeeAfterAlternatePaymentMethodPercent",
    "guarantyFeePercent",
    "interestVarianceToleranceMaximumAmount",
    "investorCollateralProgramIdentifier",
    "investorCommitmentTakeoutPricePercent",
    "investorCreditPolicyEffectiveDate",
    "investorDealIdentifier",
    "investorGroupingIdentifier",
    "investorGuarantyFeeAfterBuyupBuydownPercent",
    "investorHeldCollateralPercent",
    "investorInstitutionIdentifier",
    "investorLoanCommitmentExpirationDate",
    "investorLoanEarlyPayoffPenaltyWaiverIndicator",
    "investorLoanEffectiveDate",
    "investorLoanPartialPrepaymentPenaltyWaiverIndicator",
    "investorMasterCommitmentIdentifier",
    "investorOwnershipPercent",
    "investorOwnershipType",
    "investorProductPlanIdentifier",
    "investorRemittanceDay",
    "investorRemittanceDaysCount",
    "investorRemittanceIdentifier",
    "investorRemittanceType",
    "investorRemittanceTypeOtherDescription",
    "investorReportingMethodType",
    "investorRequiredMarginPercent",
    "investorServicingFeeAmount",
    "investorServicingFeeRatePercent",
    "lastReportedToInvestorPrincipalBalanceAmount",
    "lateDeliveryGraceDaysCount",
    "lenderTargetFundingDate",
    "loanAcquisitionScheduledUPBAmount",
    "loanBuyupBuydownBasisPointNumber",
    "loanBuyupBuydownType",
    "loanBuyupBuydownTypeOtherDescription",
    "loanDefaultedReportingFrequencyType",
    "loanDefaultLossPartyType",
    "loanDelinquencyAdvanceDaysCount",
    "loanFundingAdvancedAmount",
    "loanPriorOwnerName",
    "loanPurchaseDiscountAmount",
    "loanPurchasePremiumAmount",
    "loanServicingFeeBasisPointNumber",
    "loanServicingIndicator",
    "loanServicingRightsPurchaseOnlyIndicator",
    "loanYieldSpreadPremiumAmount",
    "loanYieldSpreadPremiumRatePercent",
    "miCoverageServicingFeeRatePercent",
    "nonStandardServicingFeeRetainedByServicerAmount",
    "passThroughCalculationMethodType",
    "passThroughCeilingRatePercent",
    "passThroughRatePercent",
    "principalVarianceToleranceMaximumAmount",
    "relatedInvestorLoanIdentifier",
    "relatedLoanInvestorType",
    "relatedLoanInvestorTypeOtherDescription",
    "removeFromTransferIndicator",
    "reoMarketingPartyType",
    "reoMarketingPartyTypeOtherDescription",
    "servicingFeeMinimumRatePercent",
    "thirdPartyLoanAcquisitionPriceAmount",
    "upbVarianceToleranceMaximumAmount",
    "warehouseAdvanceAmount",
    "warehouseCommitmentSubcategoryIdentifier",
    "wholeLoanInterestDueAmount",
    "wholeLoanPrincipalAmount",
    "wholeLoanSaleDate",
    "extension"
})
public class INVESTORLOANINFORMATION {

    @XmlElementRef(name = "BaseGuarantyFeePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> baseGuarantyFeePercent;
    @XmlElementRef(name = "ConcurrentServicingTransferIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> concurrentServicingTransferIndicator;
    @XmlElementRef(name = "ExceptionInterestAdjustmentDayMethodType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ExceptionInterestAdjustmentDayMethodEnum> exceptionInterestAdjustmentDayMethodType;
    @XmlElementRef(name = "ExcessServicingFeeRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> excessServicingFeeRatePercent;
    @XmlElementRef(name = "ExecutionType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<ExecutionEnum> executionType;
    @XmlElementRef(name = "ExecutionTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> executionTypeOtherDescription;
    @XmlElementRef(name = "FREPrimaryMortgageMarketSurveyPublishedDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> frePrimaryMortgageMarketSurveyPublishedDate;
    @XmlElementRef(name = "FREPrimaryMortgageMarketSurveyPublishedRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> frePrimaryMortgageMarketSurveyPublishedRatePercent;
    @XmlElementRef(name = "FREPrimaryMortgageMarketSurveyRoundedRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> frePrimaryMortgageMarketSurveyRoundedRatePercent;
    @XmlElementRef(name = "FundingInterestAdjustmentDayMethodType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<FundingInterestAdjustmentDayMethodEnum> fundingInterestAdjustmentDayMethodType;
    @XmlElementRef(name = "GuarantyFeeAddOnIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> guarantyFeeAddOnIndicator;
    @XmlElementRef(name = "GuarantyFeeAfterAlternatePaymentMethodPercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> guarantyFeeAfterAlternatePaymentMethodPercent;
    @XmlElementRef(name = "GuarantyFeePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> guarantyFeePercent;
    @XmlElementRef(name = "InterestVarianceToleranceMaximumAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> interestVarianceToleranceMaximumAmount;
    @XmlElementRef(name = "InvestorCollateralProgramIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorCollateralProgramIdentifier;
    @XmlElementRef(name = "InvestorCommitmentTakeoutPricePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorCommitmentTakeoutPricePercent;
    @XmlElementRef(name = "InvestorCreditPolicyEffectiveDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> investorCreditPolicyEffectiveDate;
    @XmlElementRef(name = "InvestorDealIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorDealIdentifier;
    @XmlElementRef(name = "InvestorGroupingIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorGroupingIdentifier;
    @XmlElementRef(name = "InvestorGuarantyFeeAfterBuyupBuydownPercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorGuarantyFeeAfterBuyupBuydownPercent;
    @XmlElementRef(name = "InvestorHeldCollateralPercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorHeldCollateralPercent;
    @XmlElementRef(name = "InvestorInstitutionIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorInstitutionIdentifier;
    @XmlElementRef(name = "InvestorLoanCommitmentExpirationDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> investorLoanCommitmentExpirationDate;
    @XmlElementRef(name = "InvestorLoanEarlyPayoffPenaltyWaiverIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> investorLoanEarlyPayoffPenaltyWaiverIndicator;
    @XmlElementRef(name = "InvestorLoanEffectiveDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> investorLoanEffectiveDate;
    @XmlElementRef(name = "InvestorLoanPartialPrepaymentPenaltyWaiverIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> investorLoanPartialPrepaymentPenaltyWaiverIndicator;
    @XmlElementRef(name = "InvestorMasterCommitmentIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorMasterCommitmentIdentifier;
    @XmlElementRef(name = "InvestorOwnershipPercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorOwnershipPercent;
    @XmlElementRef(name = "InvestorOwnershipType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<InvestorOwnershipEnum> investorOwnershipType;
    @XmlElementRef(name = "InvestorProductPlanIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorProductPlanIdentifier;
    @XmlElementRef(name = "InvestorRemittanceDay", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODay> investorRemittanceDay;
    @XmlElementRef(name = "InvestorRemittanceDaysCount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOCount> investorRemittanceDaysCount;
    @XmlElementRef(name = "InvestorRemittanceIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> investorRemittanceIdentifier;
    @XmlElementRef(name = "InvestorRemittanceType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<InvestorRemittanceEnum> investorRemittanceType;
    @XmlElementRef(name = "InvestorRemittanceTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> investorRemittanceTypeOtherDescription;
    @XmlElementRef(name = "InvestorReportingMethodType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<InvestorReportingMethodEnum> investorReportingMethodType;
    @XmlElementRef(name = "InvestorRequiredMarginPercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorRequiredMarginPercent;
    @XmlElementRef(name = "InvestorServicingFeeAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> investorServicingFeeAmount;
    @XmlElementRef(name = "InvestorServicingFeeRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> investorServicingFeeRatePercent;
    @XmlElementRef(name = "LastReportedToInvestorPrincipalBalanceAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> lastReportedToInvestorPrincipalBalanceAmount;
    @XmlElementRef(name = "LateDeliveryGraceDaysCount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOCount> lateDeliveryGraceDaysCount;
    @XmlElementRef(name = "LenderTargetFundingDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> lenderTargetFundingDate;
    @XmlElementRef(name = "LoanAcquisitionScheduledUPBAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> loanAcquisitionScheduledUPBAmount;
    @XmlElementRef(name = "LoanBuyupBuydownBasisPointNumber", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMONumeric> loanBuyupBuydownBasisPointNumber;
    @XmlElementRef(name = "LoanBuyupBuydownType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<LoanBuyupBuydownEnum> loanBuyupBuydownType;
    @XmlElementRef(name = "LoanBuyupBuydownTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> loanBuyupBuydownTypeOtherDescription;
    @XmlElementRef(name = "LoanDefaultedReportingFrequencyType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<LoanDefaultedReportingFrequencyEnum> loanDefaultedReportingFrequencyType;
    @XmlElementRef(name = "LoanDefaultLossPartyType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<LoanDefaultLossPartyEnum> loanDefaultLossPartyType;
    @XmlElementRef(name = "LoanDelinquencyAdvanceDaysCount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOCount> loanDelinquencyAdvanceDaysCount;
    @XmlElementRef(name = "LoanFundingAdvancedAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> loanFundingAdvancedAmount;
    @XmlElementRef(name = "LoanPriorOwnerName", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> loanPriorOwnerName;
    @XmlElementRef(name = "LoanPurchaseDiscountAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> loanPurchaseDiscountAmount;
    @XmlElementRef(name = "LoanPurchasePremiumAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> loanPurchasePremiumAmount;
    @XmlElementRef(name = "LoanServicingFeeBasisPointNumber", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMONumeric> loanServicingFeeBasisPointNumber;
    @XmlElementRef(name = "LoanServicingIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> loanServicingIndicator;
    @XmlElementRef(name = "LoanServicingRightsPurchaseOnlyIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> loanServicingRightsPurchaseOnlyIndicator;
    @XmlElementRef(name = "LoanYieldSpreadPremiumAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> loanYieldSpreadPremiumAmount;
    @XmlElementRef(name = "LoanYieldSpreadPremiumRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> loanYieldSpreadPremiumRatePercent;
    @XmlElementRef(name = "MICoverageServicingFeeRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> miCoverageServicingFeeRatePercent;
    @XmlElementRef(name = "NonStandardServicingFeeRetainedByServicerAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> nonStandardServicingFeeRetainedByServicerAmount;
    @XmlElementRef(name = "PassThroughCalculationMethodType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<PassThroughCalculationMethodEnum> passThroughCalculationMethodType;
    @XmlElementRef(name = "PassThroughCeilingRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> passThroughCeilingRatePercent;
    @XmlElementRef(name = "PassThroughRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> passThroughRatePercent;
    @XmlElementRef(name = "PrincipalVarianceToleranceMaximumAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> principalVarianceToleranceMaximumAmount;
    @XmlElementRef(name = "RelatedInvestorLoanIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> relatedInvestorLoanIdentifier;
    @XmlElementRef(name = "RelatedLoanInvestorType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<RelatedLoanInvestorEnum> relatedLoanInvestorType;
    @XmlElementRef(name = "RelatedLoanInvestorTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> relatedLoanInvestorTypeOtherDescription;
    @XmlElementRef(name = "RemoveFromTransferIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> removeFromTransferIndicator;
    @XmlElementRef(name = "REOMarketingPartyType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<REOMarketingPartyEnum> reoMarketingPartyType;
    @XmlElementRef(name = "REOMarketingPartyTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> reoMarketingPartyTypeOtherDescription;
    @XmlElementRef(name = "ServicingFeeMinimumRatePercent", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOPercent> servicingFeeMinimumRatePercent;
    @XmlElementRef(name = "ThirdPartyLoanAcquisitionPriceAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> thirdPartyLoanAcquisitionPriceAmount;
    @XmlElementRef(name = "UPBVarianceToleranceMaximumAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> upbVarianceToleranceMaximumAmount;
    @XmlElementRef(name = "WarehouseAdvanceAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> warehouseAdvanceAmount;
    @XmlElementRef(name = "WarehouseCommitmentSubcategoryIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> warehouseCommitmentSubcategoryIdentifier;
    @XmlElementRef(name = "WholeLoanInterestDueAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> wholeLoanInterestDueAmount;
    @XmlElementRef(name = "WholeLoanPrincipalAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> wholeLoanPrincipalAmount;
    @XmlElementRef(name = "WholeLoanSaleDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> wholeLoanSaleDate;
    @XmlElement(name = "EXTENSION")
    protected INVESTORLOANINFORMATIONEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the baseGuarantyFeePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getBaseGuarantyFeePercent() {
        return baseGuarantyFeePercent;
    }

    /**
     * Sets the value of the baseGuarantyFeePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setBaseGuarantyFeePercent(JAXBElement<MISMOPercent> value) {
        this.baseGuarantyFeePercent = value;
    }

    /**
     * Gets the value of the concurrentServicingTransferIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getConcurrentServicingTransferIndicator() {
        return concurrentServicingTransferIndicator;
    }

    /**
     * Sets the value of the concurrentServicingTransferIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setConcurrentServicingTransferIndicator(JAXBElement<MISMOIndicator> value) {
        this.concurrentServicingTransferIndicator = value;
    }

    /**
     * Gets the value of the exceptionInterestAdjustmentDayMethodType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExceptionInterestAdjustmentDayMethodEnum }{@code >}
     *
     */
    public JAXBElement<ExceptionInterestAdjustmentDayMethodEnum> getExceptionInterestAdjustmentDayMethodType() {
        return exceptionInterestAdjustmentDayMethodType;
    }

    /**
     * Sets the value of the exceptionInterestAdjustmentDayMethodType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExceptionInterestAdjustmentDayMethodEnum }{@code >}
     *
     */
    public void setExceptionInterestAdjustmentDayMethodType(JAXBElement<ExceptionInterestAdjustmentDayMethodEnum> value) {
        this.exceptionInterestAdjustmentDayMethodType = value;
    }

    /**
     * Gets the value of the excessServicingFeeRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getExcessServicingFeeRatePercent() {
        return excessServicingFeeRatePercent;
    }

    /**
     * Sets the value of the excessServicingFeeRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setExcessServicingFeeRatePercent(JAXBElement<MISMOPercent> value) {
        this.excessServicingFeeRatePercent = value;
    }

    /**
     * Gets the value of the executionType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExecutionEnum }{@code >}
     *
     */
    public JAXBElement<ExecutionEnum> getExecutionType() {
        return executionType;
    }

    /**
     * Sets the value of the executionType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExecutionEnum }{@code >}
     *
     */
    public void setExecutionType(JAXBElement<ExecutionEnum> value) {
        this.executionType = value;
    }

    /**
     * Gets the value of the executionTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getExecutionTypeOtherDescription() {
        return executionTypeOtherDescription;
    }

    /**
     * Sets the value of the executionTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setExecutionTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.executionTypeOtherDescription = value;
    }

    /**
     * Gets the value of the frePrimaryMortgageMarketSurveyPublishedDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getFREPrimaryMortgageMarketSurveyPublishedDate() {
        return frePrimaryMortgageMarketSurveyPublishedDate;
    }

    /**
     * Sets the value of the frePrimaryMortgageMarketSurveyPublishedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setFREPrimaryMortgageMarketSurveyPublishedDate(JAXBElement<MISMODate> value) {
        this.frePrimaryMortgageMarketSurveyPublishedDate = value;
    }

    /**
     * Gets the value of the frePrimaryMortgageMarketSurveyPublishedRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getFREPrimaryMortgageMarketSurveyPublishedRatePercent() {
        return frePrimaryMortgageMarketSurveyPublishedRatePercent;
    }

    /**
     * Sets the value of the frePrimaryMortgageMarketSurveyPublishedRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setFREPrimaryMortgageMarketSurveyPublishedRatePercent(JAXBElement<MISMOPercent> value) {
        this.frePrimaryMortgageMarketSurveyPublishedRatePercent = value;
    }

    /**
     * Gets the value of the frePrimaryMortgageMarketSurveyRoundedRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getFREPrimaryMortgageMarketSurveyRoundedRatePercent() {
        return frePrimaryMortgageMarketSurveyRoundedRatePercent;
    }

    /**
     * Sets the value of the frePrimaryMortgageMarketSurveyRoundedRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setFREPrimaryMortgageMarketSurveyRoundedRatePercent(JAXBElement<MISMOPercent> value) {
        this.frePrimaryMortgageMarketSurveyRoundedRatePercent = value;
    }

    /**
     * Gets the value of the fundingInterestAdjustmentDayMethodType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FundingInterestAdjustmentDayMethodEnum }{@code >}
     *
     */
    public JAXBElement<FundingInterestAdjustmentDayMethodEnum> getFundingInterestAdjustmentDayMethodType() {
        return fundingInterestAdjustmentDayMethodType;
    }

    /**
     * Sets the value of the fundingInterestAdjustmentDayMethodType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FundingInterestAdjustmentDayMethodEnum }{@code >}
     *
     */
    public void setFundingInterestAdjustmentDayMethodType(JAXBElement<FundingInterestAdjustmentDayMethodEnum> value) {
        this.fundingInterestAdjustmentDayMethodType = value;
    }

    /**
     * Gets the value of the guarantyFeeAddOnIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getGuarantyFeeAddOnIndicator() {
        return guarantyFeeAddOnIndicator;
    }

    /**
     * Sets the value of the guarantyFeeAddOnIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setGuarantyFeeAddOnIndicator(JAXBElement<MISMOIndicator> value) {
        this.guarantyFeeAddOnIndicator = value;
    }

    /**
     * Gets the value of the guarantyFeeAfterAlternatePaymentMethodPercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getGuarantyFeeAfterAlternatePaymentMethodPercent() {
        return guarantyFeeAfterAlternatePaymentMethodPercent;
    }

    /**
     * Sets the value of the guarantyFeeAfterAlternatePaymentMethodPercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setGuarantyFeeAfterAlternatePaymentMethodPercent(JAXBElement<MISMOPercent> value) {
        this.guarantyFeeAfterAlternatePaymentMethodPercent = value;
    }

    /**
     * Gets the value of the guarantyFeePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getGuarantyFeePercent() {
        return guarantyFeePercent;
    }

    /**
     * Sets the value of the guarantyFeePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setGuarantyFeePercent(JAXBElement<MISMOPercent> value) {
        this.guarantyFeePercent = value;
    }

    /**
     * Gets the value of the interestVarianceToleranceMaximumAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getInterestVarianceToleranceMaximumAmount() {
        return interestVarianceToleranceMaximumAmount;
    }

    /**
     * Sets the value of the interestVarianceToleranceMaximumAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setInterestVarianceToleranceMaximumAmount(JAXBElement<MISMOAmount> value) {
        this.interestVarianceToleranceMaximumAmount = value;
    }

    /**
     * Gets the value of the investorCollateralProgramIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorCollateralProgramIdentifier() {
        return investorCollateralProgramIdentifier;
    }

    /**
     * Sets the value of the investorCollateralProgramIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorCollateralProgramIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorCollateralProgramIdentifier = value;
    }

    /**
     * Gets the value of the investorCommitmentTakeoutPricePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorCommitmentTakeoutPricePercent() {
        return investorCommitmentTakeoutPricePercent;
    }

    /**
     * Sets the value of the investorCommitmentTakeoutPricePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorCommitmentTakeoutPricePercent(JAXBElement<MISMOPercent> value) {
        this.investorCommitmentTakeoutPricePercent = value;
    }

    /**
     * Gets the value of the investorCreditPolicyEffectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getInvestorCreditPolicyEffectiveDate() {
        return investorCreditPolicyEffectiveDate;
    }

    /**
     * Sets the value of the investorCreditPolicyEffectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setInvestorCreditPolicyEffectiveDate(JAXBElement<MISMODate> value) {
        this.investorCreditPolicyEffectiveDate = value;
    }

    /**
     * Gets the value of the investorDealIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorDealIdentifier() {
        return investorDealIdentifier;
    }

    /**
     * Sets the value of the investorDealIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorDealIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorDealIdentifier = value;
    }

    /**
     * Gets the value of the investorGroupingIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorGroupingIdentifier() {
        return investorGroupingIdentifier;
    }

    /**
     * Sets the value of the investorGroupingIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorGroupingIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorGroupingIdentifier = value;
    }

    /**
     * Gets the value of the investorGuarantyFeeAfterBuyupBuydownPercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorGuarantyFeeAfterBuyupBuydownPercent() {
        return investorGuarantyFeeAfterBuyupBuydownPercent;
    }

    /**
     * Sets the value of the investorGuarantyFeeAfterBuyupBuydownPercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorGuarantyFeeAfterBuyupBuydownPercent(JAXBElement<MISMOPercent> value) {
        this.investorGuarantyFeeAfterBuyupBuydownPercent = value;
    }

    /**
     * Gets the value of the investorHeldCollateralPercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorHeldCollateralPercent() {
        return investorHeldCollateralPercent;
    }

    /**
     * Sets the value of the investorHeldCollateralPercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorHeldCollateralPercent(JAXBElement<MISMOPercent> value) {
        this.investorHeldCollateralPercent = value;
    }

    /**
     * Gets the value of the investorInstitutionIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorInstitutionIdentifier() {
        return investorInstitutionIdentifier;
    }

    /**
     * Sets the value of the investorInstitutionIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorInstitutionIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorInstitutionIdentifier = value;
    }

    /**
     * Gets the value of the investorLoanCommitmentExpirationDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getInvestorLoanCommitmentExpirationDate() {
        return investorLoanCommitmentExpirationDate;
    }

    /**
     * Sets the value of the investorLoanCommitmentExpirationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setInvestorLoanCommitmentExpirationDate(JAXBElement<MISMODate> value) {
        this.investorLoanCommitmentExpirationDate = value;
    }

    /**
     * Gets the value of the investorLoanEarlyPayoffPenaltyWaiverIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getInvestorLoanEarlyPayoffPenaltyWaiverIndicator() {
        return investorLoanEarlyPayoffPenaltyWaiverIndicator;
    }

    /**
     * Sets the value of the investorLoanEarlyPayoffPenaltyWaiverIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setInvestorLoanEarlyPayoffPenaltyWaiverIndicator(JAXBElement<MISMOIndicator> value) {
        this.investorLoanEarlyPayoffPenaltyWaiverIndicator = value;
    }

    /**
     * Gets the value of the investorLoanEffectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getInvestorLoanEffectiveDate() {
        return investorLoanEffectiveDate;
    }

    /**
     * Sets the value of the investorLoanEffectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setInvestorLoanEffectiveDate(JAXBElement<MISMODate> value) {
        this.investorLoanEffectiveDate = value;
    }

    /**
     * Gets the value of the investorLoanPartialPrepaymentPenaltyWaiverIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getInvestorLoanPartialPrepaymentPenaltyWaiverIndicator() {
        return investorLoanPartialPrepaymentPenaltyWaiverIndicator;
    }

    /**
     * Sets the value of the investorLoanPartialPrepaymentPenaltyWaiverIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setInvestorLoanPartialPrepaymentPenaltyWaiverIndicator(JAXBElement<MISMOIndicator> value) {
        this.investorLoanPartialPrepaymentPenaltyWaiverIndicator = value;
    }

    /**
     * Gets the value of the investorMasterCommitmentIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorMasterCommitmentIdentifier() {
        return investorMasterCommitmentIdentifier;
    }

    /**
     * Sets the value of the investorMasterCommitmentIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorMasterCommitmentIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorMasterCommitmentIdentifier = value;
    }

    /**
     * Gets the value of the investorOwnershipPercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorOwnershipPercent() {
        return investorOwnershipPercent;
    }

    /**
     * Sets the value of the investorOwnershipPercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorOwnershipPercent(JAXBElement<MISMOPercent> value) {
        this.investorOwnershipPercent = value;
    }

    /**
     * Gets the value of the investorOwnershipType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link InvestorOwnershipEnum }{@code >}
     *
     */
    public JAXBElement<InvestorOwnershipEnum> getInvestorOwnershipType() {
        return investorOwnershipType;
    }

    /**
     * Sets the value of the investorOwnershipType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link InvestorOwnershipEnum }{@code >}
     *
     */
    public void setInvestorOwnershipType(JAXBElement<InvestorOwnershipEnum> value) {
        this.investorOwnershipType = value;
    }

    /**
     * Gets the value of the investorProductPlanIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorProductPlanIdentifier() {
        return investorProductPlanIdentifier;
    }

    /**
     * Sets the value of the investorProductPlanIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorProductPlanIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorProductPlanIdentifier = value;
    }

    /**
     * Gets the value of the investorRemittanceDay property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODay }{@code >}
     *
     */
    public JAXBElement<MISMODay> getInvestorRemittanceDay() {
        return investorRemittanceDay;
    }

    /**
     * Sets the value of the investorRemittanceDay property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODay }{@code >}
     *
     */
    public void setInvestorRemittanceDay(JAXBElement<MISMODay> value) {
        this.investorRemittanceDay = value;
    }

    /**
     * Gets the value of the investorRemittanceDaysCount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public JAXBElement<MISMOCount> getInvestorRemittanceDaysCount() {
        return investorRemittanceDaysCount;
    }

    /**
     * Sets the value of the investorRemittanceDaysCount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public void setInvestorRemittanceDaysCount(JAXBElement<MISMOCount> value) {
        this.investorRemittanceDaysCount = value;
    }

    /**
     * Gets the value of the investorRemittanceIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getInvestorRemittanceIdentifier() {
        return investorRemittanceIdentifier;
    }

    /**
     * Sets the value of the investorRemittanceIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setInvestorRemittanceIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.investorRemittanceIdentifier = value;
    }

    /**
     * Gets the value of the investorRemittanceType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link InvestorRemittanceEnum }{@code >}
     *
     */
    public JAXBElement<InvestorRemittanceEnum> getInvestorRemittanceType() {
        return investorRemittanceType;
    }

    /**
     * Sets the value of the investorRemittanceType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link InvestorRemittanceEnum }{@code >}
     *
     */
    public void setInvestorRemittanceType(JAXBElement<InvestorRemittanceEnum> value) {
        this.investorRemittanceType = value;
    }

    /**
     * Gets the value of the investorRemittanceTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getInvestorRemittanceTypeOtherDescription() {
        return investorRemittanceTypeOtherDescription;
    }

    /**
     * Sets the value of the investorRemittanceTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setInvestorRemittanceTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.investorRemittanceTypeOtherDescription = value;
    }

    /**
     * Gets the value of the investorReportingMethodType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link InvestorReportingMethodEnum }{@code >}
     *
     */
    public JAXBElement<InvestorReportingMethodEnum> getInvestorReportingMethodType() {
        return investorReportingMethodType;
    }

    /**
     * Sets the value of the investorReportingMethodType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link InvestorReportingMethodEnum }{@code >}
     *
     */
    public void setInvestorReportingMethodType(JAXBElement<InvestorReportingMethodEnum> value) {
        this.investorReportingMethodType = value;
    }

    /**
     * Gets the value of the investorRequiredMarginPercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorRequiredMarginPercent() {
        return investorRequiredMarginPercent;
    }

    /**
     * Sets the value of the investorRequiredMarginPercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorRequiredMarginPercent(JAXBElement<MISMOPercent> value) {
        this.investorRequiredMarginPercent = value;
    }

    /**
     * Gets the value of the investorServicingFeeAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getInvestorServicingFeeAmount() {
        return investorServicingFeeAmount;
    }

    /**
     * Sets the value of the investorServicingFeeAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setInvestorServicingFeeAmount(JAXBElement<MISMOAmount> value) {
        this.investorServicingFeeAmount = value;
    }

    /**
     * Gets the value of the investorServicingFeeRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getInvestorServicingFeeRatePercent() {
        return investorServicingFeeRatePercent;
    }

    /**
     * Sets the value of the investorServicingFeeRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setInvestorServicingFeeRatePercent(JAXBElement<MISMOPercent> value) {
        this.investorServicingFeeRatePercent = value;
    }

    /**
     * Gets the value of the lastReportedToInvestorPrincipalBalanceAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLastReportedToInvestorPrincipalBalanceAmount() {
        return lastReportedToInvestorPrincipalBalanceAmount;
    }

    /**
     * Sets the value of the lastReportedToInvestorPrincipalBalanceAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLastReportedToInvestorPrincipalBalanceAmount(JAXBElement<MISMOAmount> value) {
        this.lastReportedToInvestorPrincipalBalanceAmount = value;
    }

    /**
     * Gets the value of the lateDeliveryGraceDaysCount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public JAXBElement<MISMOCount> getLateDeliveryGraceDaysCount() {
        return lateDeliveryGraceDaysCount;
    }

    /**
     * Sets the value of the lateDeliveryGraceDaysCount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public void setLateDeliveryGraceDaysCount(JAXBElement<MISMOCount> value) {
        this.lateDeliveryGraceDaysCount = value;
    }

    /**
     * Gets the value of the lenderTargetFundingDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getLenderTargetFundingDate() {
        return lenderTargetFundingDate;
    }

    /**
     * Sets the value of the lenderTargetFundingDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setLenderTargetFundingDate(JAXBElement<MISMODate> value) {
        this.lenderTargetFundingDate = value;
    }

    /**
     * Gets the value of the loanAcquisitionScheduledUPBAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLoanAcquisitionScheduledUPBAmount() {
        return loanAcquisitionScheduledUPBAmount;
    }

    /**
     * Sets the value of the loanAcquisitionScheduledUPBAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLoanAcquisitionScheduledUPBAmount(JAXBElement<MISMOAmount> value) {
        this.loanAcquisitionScheduledUPBAmount = value;
    }

    /**
     * Gets the value of the loanBuyupBuydownBasisPointNumber property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMONumeric }{@code >}
     *
     */
    public JAXBElement<MISMONumeric> getLoanBuyupBuydownBasisPointNumber() {
        return loanBuyupBuydownBasisPointNumber;
    }

    /**
     * Sets the value of the loanBuyupBuydownBasisPointNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMONumeric }{@code >}
     *
     */
    public void setLoanBuyupBuydownBasisPointNumber(JAXBElement<MISMONumeric> value) {
        this.loanBuyupBuydownBasisPointNumber = value;
    }

    /**
     * Gets the value of the loanBuyupBuydownType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LoanBuyupBuydownEnum }{@code >}
     *
     */
    public JAXBElement<LoanBuyupBuydownEnum> getLoanBuyupBuydownType() {
        return loanBuyupBuydownType;
    }

    /**
     * Sets the value of the loanBuyupBuydownType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LoanBuyupBuydownEnum }{@code >}
     *
     */
    public void setLoanBuyupBuydownType(JAXBElement<LoanBuyupBuydownEnum> value) {
        this.loanBuyupBuydownType = value;
    }

    /**
     * Gets the value of the loanBuyupBuydownTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getLoanBuyupBuydownTypeOtherDescription() {
        return loanBuyupBuydownTypeOtherDescription;
    }

    /**
     * Sets the value of the loanBuyupBuydownTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setLoanBuyupBuydownTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.loanBuyupBuydownTypeOtherDescription = value;
    }

    /**
     * Gets the value of the loanDefaultedReportingFrequencyType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LoanDefaultedReportingFrequencyEnum }{@code >}
     *
     */
    public JAXBElement<LoanDefaultedReportingFrequencyEnum> getLoanDefaultedReportingFrequencyType() {
        return loanDefaultedReportingFrequencyType;
    }

    /**
     * Sets the value of the loanDefaultedReportingFrequencyType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LoanDefaultedReportingFrequencyEnum }{@code >}
     *
     */
    public void setLoanDefaultedReportingFrequencyType(JAXBElement<LoanDefaultedReportingFrequencyEnum> value) {
        this.loanDefaultedReportingFrequencyType = value;
    }

    /**
     * Gets the value of the loanDefaultLossPartyType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LoanDefaultLossPartyEnum }{@code >}
     *
     */
    public JAXBElement<LoanDefaultLossPartyEnum> getLoanDefaultLossPartyType() {
        return loanDefaultLossPartyType;
    }

    /**
     * Sets the value of the loanDefaultLossPartyType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LoanDefaultLossPartyEnum }{@code >}
     *
     */
    public void setLoanDefaultLossPartyType(JAXBElement<LoanDefaultLossPartyEnum> value) {
        this.loanDefaultLossPartyType = value;
    }

    /**
     * Gets the value of the loanDelinquencyAdvanceDaysCount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public JAXBElement<MISMOCount> getLoanDelinquencyAdvanceDaysCount() {
        return loanDelinquencyAdvanceDaysCount;
    }

    /**
     * Sets the value of the loanDelinquencyAdvanceDaysCount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOCount }{@code >}
     *
     */
    public void setLoanDelinquencyAdvanceDaysCount(JAXBElement<MISMOCount> value) {
        this.loanDelinquencyAdvanceDaysCount = value;
    }

    /**
     * Gets the value of the loanFundingAdvancedAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLoanFundingAdvancedAmount() {
        return loanFundingAdvancedAmount;
    }

    /**
     * Sets the value of the loanFundingAdvancedAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLoanFundingAdvancedAmount(JAXBElement<MISMOAmount> value) {
        this.loanFundingAdvancedAmount = value;
    }

    /**
     * Gets the value of the loanPriorOwnerName property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getLoanPriorOwnerName() {
        return loanPriorOwnerName;
    }

    /**
     * Sets the value of the loanPriorOwnerName property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setLoanPriorOwnerName(JAXBElement<MISMOString> value) {
        this.loanPriorOwnerName = value;
    }

    /**
     * Gets the value of the loanPurchaseDiscountAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLoanPurchaseDiscountAmount() {
        return loanPurchaseDiscountAmount;
    }

    /**
     * Sets the value of the loanPurchaseDiscountAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLoanPurchaseDiscountAmount(JAXBElement<MISMOAmount> value) {
        this.loanPurchaseDiscountAmount = value;
    }

    /**
     * Gets the value of the loanPurchasePremiumAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLoanPurchasePremiumAmount() {
        return loanPurchasePremiumAmount;
    }

    /**
     * Sets the value of the loanPurchasePremiumAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLoanPurchasePremiumAmount(JAXBElement<MISMOAmount> value) {
        this.loanPurchasePremiumAmount = value;
    }

    /**
     * Gets the value of the loanServicingFeeBasisPointNumber property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMONumeric }{@code >}
     *
     */
    public JAXBElement<MISMONumeric> getLoanServicingFeeBasisPointNumber() {
        return loanServicingFeeBasisPointNumber;
    }

    /**
     * Sets the value of the loanServicingFeeBasisPointNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMONumeric }{@code >}
     *
     */
    public void setLoanServicingFeeBasisPointNumber(JAXBElement<MISMONumeric> value) {
        this.loanServicingFeeBasisPointNumber = value;
    }

    /**
     * Gets the value of the loanServicingIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getLoanServicingIndicator() {
        return loanServicingIndicator;
    }

    /**
     * Sets the value of the loanServicingIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setLoanServicingIndicator(JAXBElement<MISMOIndicator> value) {
        this.loanServicingIndicator = value;
    }

    /**
     * Gets the value of the loanServicingRightsPurchaseOnlyIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getLoanServicingRightsPurchaseOnlyIndicator() {
        return loanServicingRightsPurchaseOnlyIndicator;
    }

    /**
     * Sets the value of the loanServicingRightsPurchaseOnlyIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setLoanServicingRightsPurchaseOnlyIndicator(JAXBElement<MISMOIndicator> value) {
        this.loanServicingRightsPurchaseOnlyIndicator = value;
    }

    /**
     * Gets the value of the loanYieldSpreadPremiumAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getLoanYieldSpreadPremiumAmount() {
        return loanYieldSpreadPremiumAmount;
    }

    /**
     * Sets the value of the loanYieldSpreadPremiumAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setLoanYieldSpreadPremiumAmount(JAXBElement<MISMOAmount> value) {
        this.loanYieldSpreadPremiumAmount = value;
    }

    /**
     * Gets the value of the loanYieldSpreadPremiumRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getLoanYieldSpreadPremiumRatePercent() {
        return loanYieldSpreadPremiumRatePercent;
    }

    /**
     * Sets the value of the loanYieldSpreadPremiumRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setLoanYieldSpreadPremiumRatePercent(JAXBElement<MISMOPercent> value) {
        this.loanYieldSpreadPremiumRatePercent = value;
    }

    /**
     * Gets the value of the miCoverageServicingFeeRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getMICoverageServicingFeeRatePercent() {
        return miCoverageServicingFeeRatePercent;
    }

    /**
     * Sets the value of the miCoverageServicingFeeRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setMICoverageServicingFeeRatePercent(JAXBElement<MISMOPercent> value) {
        this.miCoverageServicingFeeRatePercent = value;
    }

    /**
     * Gets the value of the nonStandardServicingFeeRetainedByServicerAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getNonStandardServicingFeeRetainedByServicerAmount() {
        return nonStandardServicingFeeRetainedByServicerAmount;
    }

    /**
     * Sets the value of the nonStandardServicingFeeRetainedByServicerAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setNonStandardServicingFeeRetainedByServicerAmount(JAXBElement<MISMOAmount> value) {
        this.nonStandardServicingFeeRetainedByServicerAmount = value;
    }

    /**
     * Gets the value of the passThroughCalculationMethodType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PassThroughCalculationMethodEnum }{@code >}
     *
     */
    public JAXBElement<PassThroughCalculationMethodEnum> getPassThroughCalculationMethodType() {
        return passThroughCalculationMethodType;
    }

    /**
     * Sets the value of the passThroughCalculationMethodType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PassThroughCalculationMethodEnum }{@code >}
     *
     */
    public void setPassThroughCalculationMethodType(JAXBElement<PassThroughCalculationMethodEnum> value) {
        this.passThroughCalculationMethodType = value;
    }

    /**
     * Gets the value of the passThroughCeilingRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getPassThroughCeilingRatePercent() {
        return passThroughCeilingRatePercent;
    }

    /**
     * Sets the value of the passThroughCeilingRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setPassThroughCeilingRatePercent(JAXBElement<MISMOPercent> value) {
        this.passThroughCeilingRatePercent = value;
    }

    /**
     * Gets the value of the passThroughRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getPassThroughRatePercent() {
        return passThroughRatePercent;
    }

    /**
     * Sets the value of the passThroughRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setPassThroughRatePercent(JAXBElement<MISMOPercent> value) {
        this.passThroughRatePercent = value;
    }

    /**
     * Gets the value of the principalVarianceToleranceMaximumAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getPrincipalVarianceToleranceMaximumAmount() {
        return principalVarianceToleranceMaximumAmount;
    }

    /**
     * Sets the value of the principalVarianceToleranceMaximumAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setPrincipalVarianceToleranceMaximumAmount(JAXBElement<MISMOAmount> value) {
        this.principalVarianceToleranceMaximumAmount = value;
    }

    /**
     * Gets the value of the relatedInvestorLoanIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getRelatedInvestorLoanIdentifier() {
        return relatedInvestorLoanIdentifier;
    }

    /**
     * Sets the value of the relatedInvestorLoanIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setRelatedInvestorLoanIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.relatedInvestorLoanIdentifier = value;
    }

    /**
     * Gets the value of the relatedLoanInvestorType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RelatedLoanInvestorEnum }{@code >}
     *
     */
    public JAXBElement<RelatedLoanInvestorEnum> getRelatedLoanInvestorType() {
        return relatedLoanInvestorType;
    }

    /**
     * Sets the value of the relatedLoanInvestorType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RelatedLoanInvestorEnum }{@code >}
     *
     */
    public void setRelatedLoanInvestorType(JAXBElement<RelatedLoanInvestorEnum> value) {
        this.relatedLoanInvestorType = value;
    }

    /**
     * Gets the value of the relatedLoanInvestorTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getRelatedLoanInvestorTypeOtherDescription() {
        return relatedLoanInvestorTypeOtherDescription;
    }

    /**
     * Sets the value of the relatedLoanInvestorTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setRelatedLoanInvestorTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.relatedLoanInvestorTypeOtherDescription = value;
    }

    /**
     * Gets the value of the removeFromTransferIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getRemoveFromTransferIndicator() {
        return removeFromTransferIndicator;
    }

    /**
     * Sets the value of the removeFromTransferIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setRemoveFromTransferIndicator(JAXBElement<MISMOIndicator> value) {
        this.removeFromTransferIndicator = value;
    }

    /**
     * Gets the value of the reoMarketingPartyType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REOMarketingPartyEnum }{@code >}
     *
     */
    public JAXBElement<REOMarketingPartyEnum> getREOMarketingPartyType() {
        return reoMarketingPartyType;
    }

    /**
     * Sets the value of the reoMarketingPartyType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REOMarketingPartyEnum }{@code >}
     *
     */
    public void setREOMarketingPartyType(JAXBElement<REOMarketingPartyEnum> value) {
        this.reoMarketingPartyType = value;
    }

    /**
     * Gets the value of the reoMarketingPartyTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getREOMarketingPartyTypeOtherDescription() {
        return reoMarketingPartyTypeOtherDescription;
    }

    /**
     * Sets the value of the reoMarketingPartyTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setREOMarketingPartyTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.reoMarketingPartyTypeOtherDescription = value;
    }

    /**
     * Gets the value of the servicingFeeMinimumRatePercent property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public JAXBElement<MISMOPercent> getServicingFeeMinimumRatePercent() {
        return servicingFeeMinimumRatePercent;
    }

    /**
     * Sets the value of the servicingFeeMinimumRatePercent property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOPercent }{@code >}
     *
     */
    public void setServicingFeeMinimumRatePercent(JAXBElement<MISMOPercent> value) {
        this.servicingFeeMinimumRatePercent = value;
    }

    /**
     * Gets the value of the thirdPartyLoanAcquisitionPriceAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getThirdPartyLoanAcquisitionPriceAmount() {
        return thirdPartyLoanAcquisitionPriceAmount;
    }

    /**
     * Sets the value of the thirdPartyLoanAcquisitionPriceAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setThirdPartyLoanAcquisitionPriceAmount(JAXBElement<MISMOAmount> value) {
        this.thirdPartyLoanAcquisitionPriceAmount = value;
    }

    /**
     * Gets the value of the upbVarianceToleranceMaximumAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getUPBVarianceToleranceMaximumAmount() {
        return upbVarianceToleranceMaximumAmount;
    }

    /**
     * Sets the value of the upbVarianceToleranceMaximumAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setUPBVarianceToleranceMaximumAmount(JAXBElement<MISMOAmount> value) {
        this.upbVarianceToleranceMaximumAmount = value;
    }

    /**
     * Gets the value of the warehouseAdvanceAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getWarehouseAdvanceAmount() {
        return warehouseAdvanceAmount;
    }

    /**
     * Sets the value of the warehouseAdvanceAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setWarehouseAdvanceAmount(JAXBElement<MISMOAmount> value) {
        this.warehouseAdvanceAmount = value;
    }

    /**
     * Gets the value of the warehouseCommitmentSubcategoryIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getWarehouseCommitmentSubcategoryIdentifier() {
        return warehouseCommitmentSubcategoryIdentifier;
    }

    /**
     * Sets the value of the warehouseCommitmentSubcategoryIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setWarehouseCommitmentSubcategoryIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.warehouseCommitmentSubcategoryIdentifier = value;
    }

    /**
     * Gets the value of the wholeLoanInterestDueAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getWholeLoanInterestDueAmount() {
        return wholeLoanInterestDueAmount;
    }

    /**
     * Sets the value of the wholeLoanInterestDueAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setWholeLoanInterestDueAmount(JAXBElement<MISMOAmount> value) {
        this.wholeLoanInterestDueAmount = value;
    }

    /**
     * Gets the value of the wholeLoanPrincipalAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getWholeLoanPrincipalAmount() {
        return wholeLoanPrincipalAmount;
    }

    /**
     * Sets the value of the wholeLoanPrincipalAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setWholeLoanPrincipalAmount(JAXBElement<MISMOAmount> value) {
        this.wholeLoanPrincipalAmount = value;
    }

    /**
     * Gets the value of the wholeLoanSaleDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getWholeLoanSaleDate() {
        return wholeLoanSaleDate;
    }

    /**
     * Sets the value of the wholeLoanSaleDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setWholeLoanSaleDate(JAXBElement<MISMODate> value) {
        this.wholeLoanSaleDate = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link INVESTORLOANINFORMATIONEXTENSION }
     *
     */
    public INVESTORLOANINFORMATIONEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link INVESTORLOANINFORMATIONEXTENSION }
     *
     */
    public void setEXTENSION(INVESTORLOANINFORMATIONEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
