//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * A property description, recognized by law, that is sufficient to locate and identify the property without oral testimony.
 *
 * <p>Java class for LEGAL_DESCRIPTION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LEGAL_DESCRIPTION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PARCEL_IDENTIFICATIONS" type="{http://www.mismo.org/residential/2009/schemas}PARCEL_IDENTIFICATIONS" minOccurs="0"/>
 *         &lt;element name="PARSED_LEGAL_DESCRIPTION" type="{http://www.mismo.org/residential/2009/schemas}PARSED_LEGAL_DESCRIPTION" minOccurs="0"/>
 *         &lt;element name="UNPARSED_LEGAL_DESCRIPTIONS" type="{http://www.mismo.org/residential/2009/schemas}UNPARSED_LEGAL_DESCRIPTIONS" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}LEGAL_DESCRIPTION_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;attribute name="SequenceNumber" type="{http://www.mismo.org/residential/2009/schemas}MISMOSequenceNumber_Base" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGAL_DESCRIPTION", propOrder = {
    "parcelidentifications",
    "parsedlegaldescription",
    "unparsedlegaldescriptions",
    "extension"
})
public class LEGALDESCRIPTION {

    @XmlElement(name = "PARCEL_IDENTIFICATIONS")
    protected PARCELIDENTIFICATIONS parcelidentifications;
    @XmlElement(name = "PARSED_LEGAL_DESCRIPTION")
    protected PARSEDLEGALDESCRIPTION parsedlegaldescription;
    @XmlElement(name = "UNPARSED_LEGAL_DESCRIPTIONS")
    protected UNPARSEDLEGALDESCRIPTIONS unparsedlegaldescriptions;
    @XmlElement(name = "EXTENSION")
    protected LEGALDESCRIPTIONEXTENSION extension;
    @XmlAttribute(name = "SequenceNumber")
    protected Integer sequenceNumber;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the parcelidentifications property.
     *
     * @return
     *     possible object is
     *     {@link PARCELIDENTIFICATIONS }
     *
     */
    public PARCELIDENTIFICATIONS getPARCELIDENTIFICATIONS() {
        return parcelidentifications;
    }

    /**
     * Sets the value of the parcelidentifications property.
     *
     * @param value
     *     allowed object is
     *     {@link PARCELIDENTIFICATIONS }
     *
     */
    public void setPARCELIDENTIFICATIONS(PARCELIDENTIFICATIONS value) {
        this.parcelidentifications = value;
    }

    /**
     * Gets the value of the parsedlegaldescription property.
     *
     * @return
     *     possible object is
     *     {@link PARSEDLEGALDESCRIPTION }
     *
     */
    public PARSEDLEGALDESCRIPTION getPARSEDLEGALDESCRIPTION() {
        return parsedlegaldescription;
    }

    /**
     * Sets the value of the parsedlegaldescription property.
     *
     * @param value
     *     allowed object is
     *     {@link PARSEDLEGALDESCRIPTION }
     *
     */
    public void setPARSEDLEGALDESCRIPTION(PARSEDLEGALDESCRIPTION value) {
        this.parsedlegaldescription = value;
    }

    /**
     * Gets the value of the unparsedlegaldescriptions property.
     *
     * @return
     *     possible object is
     *     {@link UNPARSEDLEGALDESCRIPTIONS }
     *
     */
    public UNPARSEDLEGALDESCRIPTIONS getUNPARSEDLEGALDESCRIPTIONS() {
        return unparsedlegaldescriptions;
    }

    /**
     * Sets the value of the unparsedlegaldescriptions property.
     *
     * @param value
     *     allowed object is
     *     {@link UNPARSEDLEGALDESCRIPTIONS }
     *
     */
    public void setUNPARSEDLEGALDESCRIPTIONS(UNPARSEDLEGALDESCRIPTIONS value) {
        this.unparsedlegaldescriptions = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link LEGALDESCRIPTIONEXTENSION }
     *
     */
    public LEGALDESCRIPTIONEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link LEGALDESCRIPTIONEXTENSION }
     *
     */
    public void setEXTENSION(LEGALDESCRIPTIONEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setSequenceNumber(Integer value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
