//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for REGULATORY_AGENCY complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="REGULATORY_AGENCY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegulatoryAgencyType" type="{http://www.mismo.org/residential/2009/schemas}RegulatoryAgencyEnum" minOccurs="0"/>
 *         &lt;element name="RegulatoryAgencyTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}REGULATORY_AGENCY_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REGULATORY_AGENCY", propOrder = {
    "regulatoryAgencyType",
    "regulatoryAgencyTypeOtherDescription",
    "extension"
})
public class REGULATORYAGENCY {

    @XmlElementRef(name = "RegulatoryAgencyType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<RegulatoryAgencyEnum> regulatoryAgencyType;
    @XmlElementRef(name = "RegulatoryAgencyTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> regulatoryAgencyTypeOtherDescription;
    @XmlElement(name = "EXTENSION")
    protected REGULATORYAGENCYEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the regulatoryAgencyType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RegulatoryAgencyEnum }{@code >}
     *
     */
    public JAXBElement<RegulatoryAgencyEnum> getRegulatoryAgencyType() {
        return regulatoryAgencyType;
    }

    /**
     * Sets the value of the regulatoryAgencyType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RegulatoryAgencyEnum }{@code >}
     *
     */
    public void setRegulatoryAgencyType(JAXBElement<RegulatoryAgencyEnum> value) {
        this.regulatoryAgencyType = value;
    }

    /**
     * Gets the value of the regulatoryAgencyTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getRegulatoryAgencyTypeOtherDescription() {
        return regulatoryAgencyTypeOtherDescription;
    }

    /**
     * Sets the value of the regulatoryAgencyTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setRegulatoryAgencyTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.regulatoryAgencyTypeOtherDescription = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link REGULATORYAGENCYEXTENSION }
     *
     */
    public REGULATORYAGENCYEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link REGULATORYAGENCYEXTENSION }
     *
     */
    public void setEXTENSION(REGULATORYAGENCYEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
