//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for SITE_UTILITY complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SITE_UTILITY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SiteUndergroundUtilitiesIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="SiteUtilityAlternativeEnergySourceType" type="{http://www.mismo.org/residential/2009/schemas}SiteUtilityAlternativeEnergySourceEnum" minOccurs="0"/>
 *         &lt;element name="SiteUtilityAlternativeEnergySourceTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SiteUtilityNonPublicOwnershipDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SiteUtilityNotTypicalDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SiteUtilityOwnershipType" type="{http://www.mismo.org/residential/2009/schemas}SiteUtilityOwnershipEnum" minOccurs="0"/>
 *         &lt;element name="SiteUtilityType" type="{http://www.mismo.org/residential/2009/schemas}SiteUtilityEnum" minOccurs="0"/>
 *         &lt;element name="SiteUtilityTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="UtilityTypicalIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}SITE_UTILITY_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;attribute name="SequenceNumber" type="{http://www.mismo.org/residential/2009/schemas}MISMOSequenceNumber_Base" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SITE_UTILITY", propOrder = {
    "siteUndergroundUtilitiesIndicator",
    "siteUtilityAlternativeEnergySourceType",
    "siteUtilityAlternativeEnergySourceTypeOtherDescription",
    "siteUtilityNonPublicOwnershipDescription",
    "siteUtilityNotTypicalDescription",
    "siteUtilityOwnershipType",
    "siteUtilityType",
    "siteUtilityTypeOtherDescription",
    "utilityTypicalIndicator",
    "extension"
})
public class SITEUTILITY {

    @XmlElementRef(name = "SiteUndergroundUtilitiesIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> siteUndergroundUtilitiesIndicator;
    @XmlElementRef(name = "SiteUtilityAlternativeEnergySourceType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<SiteUtilityAlternativeEnergySourceEnum> siteUtilityAlternativeEnergySourceType;
    @XmlElementRef(name = "SiteUtilityAlternativeEnergySourceTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> siteUtilityAlternativeEnergySourceTypeOtherDescription;
    @XmlElementRef(name = "SiteUtilityNonPublicOwnershipDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> siteUtilityNonPublicOwnershipDescription;
    @XmlElementRef(name = "SiteUtilityNotTypicalDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> siteUtilityNotTypicalDescription;
    @XmlElementRef(name = "SiteUtilityOwnershipType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<SiteUtilityOwnershipEnum> siteUtilityOwnershipType;
    @XmlElementRef(name = "SiteUtilityType", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<SiteUtilityEnum> siteUtilityType;
    @XmlElementRef(name = "SiteUtilityTypeOtherDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> siteUtilityTypeOtherDescription;
    @XmlElementRef(name = "UtilityTypicalIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> utilityTypicalIndicator;
    @XmlElement(name = "EXTENSION")
    protected SITEUTILITYEXTENSION extension;
    @XmlAttribute(name = "SequenceNumber")
    protected Integer sequenceNumber;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the siteUndergroundUtilitiesIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getSiteUndergroundUtilitiesIndicator() {
        return siteUndergroundUtilitiesIndicator;
    }

    /**
     * Sets the value of the siteUndergroundUtilitiesIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setSiteUndergroundUtilitiesIndicator(JAXBElement<MISMOIndicator> value) {
        this.siteUndergroundUtilitiesIndicator = value;
    }

    /**
     * Gets the value of the siteUtilityAlternativeEnergySourceType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityAlternativeEnergySourceEnum }{@code >}
     *
     */
    public JAXBElement<SiteUtilityAlternativeEnergySourceEnum> getSiteUtilityAlternativeEnergySourceType() {
        return siteUtilityAlternativeEnergySourceType;
    }

    /**
     * Sets the value of the siteUtilityAlternativeEnergySourceType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityAlternativeEnergySourceEnum }{@code >}
     *
     */
    public void setSiteUtilityAlternativeEnergySourceType(JAXBElement<SiteUtilityAlternativeEnergySourceEnum> value) {
        this.siteUtilityAlternativeEnergySourceType = value;
    }

    /**
     * Gets the value of the siteUtilityAlternativeEnergySourceTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getSiteUtilityAlternativeEnergySourceTypeOtherDescription() {
        return siteUtilityAlternativeEnergySourceTypeOtherDescription;
    }

    /**
     * Sets the value of the siteUtilityAlternativeEnergySourceTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setSiteUtilityAlternativeEnergySourceTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.siteUtilityAlternativeEnergySourceTypeOtherDescription = value;
    }

    /**
     * Gets the value of the siteUtilityNonPublicOwnershipDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getSiteUtilityNonPublicOwnershipDescription() {
        return siteUtilityNonPublicOwnershipDescription;
    }

    /**
     * Sets the value of the siteUtilityNonPublicOwnershipDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setSiteUtilityNonPublicOwnershipDescription(JAXBElement<MISMOString> value) {
        this.siteUtilityNonPublicOwnershipDescription = value;
    }

    /**
     * Gets the value of the siteUtilityNotTypicalDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getSiteUtilityNotTypicalDescription() {
        return siteUtilityNotTypicalDescription;
    }

    /**
     * Sets the value of the siteUtilityNotTypicalDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setSiteUtilityNotTypicalDescription(JAXBElement<MISMOString> value) {
        this.siteUtilityNotTypicalDescription = value;
    }

    /**
     * Gets the value of the siteUtilityOwnershipType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityOwnershipEnum }{@code >}
     *
     */
    public JAXBElement<SiteUtilityOwnershipEnum> getSiteUtilityOwnershipType() {
        return siteUtilityOwnershipType;
    }

    /**
     * Sets the value of the siteUtilityOwnershipType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityOwnershipEnum }{@code >}
     *
     */
    public void setSiteUtilityOwnershipType(JAXBElement<SiteUtilityOwnershipEnum> value) {
        this.siteUtilityOwnershipType = value;
    }

    /**
     * Gets the value of the siteUtilityType property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityEnum }{@code >}
     *
     */
    public JAXBElement<SiteUtilityEnum> getSiteUtilityType() {
        return siteUtilityType;
    }

    /**
     * Sets the value of the siteUtilityType property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SiteUtilityEnum }{@code >}
     *
     */
    public void setSiteUtilityType(JAXBElement<SiteUtilityEnum> value) {
        this.siteUtilityType = value;
    }

    /**
     * Gets the value of the siteUtilityTypeOtherDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getSiteUtilityTypeOtherDescription() {
        return siteUtilityTypeOtherDescription;
    }

    /**
     * Sets the value of the siteUtilityTypeOtherDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setSiteUtilityTypeOtherDescription(JAXBElement<MISMOString> value) {
        this.siteUtilityTypeOtherDescription = value;
    }

    /**
     * Gets the value of the utilityTypicalIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getUtilityTypicalIndicator() {
        return utilityTypicalIndicator;
    }

    /**
     * Sets the value of the utilityTypicalIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setUtilityTypicalIndicator(JAXBElement<MISMOIndicator> value) {
        this.utilityTypicalIndicator = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link SITEUTILITYEXTENSION }
     *
     */
    public SITEUTILITYEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link SITEUTILITYEXTENSION }
     *
     */
    public void setEXTENSION(SITEUTILITYEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setSequenceNumber(Integer value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
