//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TitleRequestActionBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TitleRequestActionBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Cancellation"/>
 *     &lt;enumeration value="Change"/>
 *     &lt;enumeration value="ERemittance"/>
 *     &lt;enumeration value="GetDocument"/>
 *     &lt;enumeration value="Original"/>
 *     &lt;enumeration value="PriceQuote"/>
 *     &lt;enumeration value="StatusQuery"/>
 *     &lt;enumeration value="Update"/>
 *     &lt;enumeration value="ValidateAgent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "TitleRequestActionBase")
@XmlEnum
public enum TitleRequestActionBase {


    /**
     * Indicates that this order is to be cancelled.
     *
     */
    @XmlEnumValue("Cancellation")
    CANCELLATION("Cancellation"),

    /**
     * Indicates a change to a previously placed order.
     *
     */
    @XmlEnumValue("Change")
    CHANGE("Change"),

    /**
     * Indicates that there is a request for an Agent to perform eRemittance to the underwriter.
     *
     */
    @XmlEnumValue("ERemittance")
    E_REMITTANCE("ERemittance"),

    /**
     * Indicates that there is a request for a document and/or data to be delivered.
     *
     */
    @XmlEnumValue("GetDocument")
    GET_DOCUMENT("GetDocument"),

    /**
     * Indicates that this is the original order.
     *
     */
    @XmlEnumValue("Original")
    ORIGINAL("Original"),

    /**
     * Indicates that this request is merely for a price for a particular title policy.
     *
     */
    @XmlEnumValue("PriceQuote")
    PRICE_QUOTE("PriceQuote"),

    /**
     * Indicates that this is a request for status on a previously placed title order.
     *
     */
    @XmlEnumValue("StatusQuery")
    STATUS_QUERY("StatusQuery"),

    /**
     * Indicates that this request will update a previously placed title order.
     *
     */
    @XmlEnumValue("Update")
    UPDATE("Update"),

    /**
     * Indicates that this is a request for an agent validation transaction on an order.
     *
     */
    @XmlEnumValue("ValidateAgent")
    VALIDATE_AGENT("ValidateAgent");
    private final String value;

    TitleRequestActionBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TitleRequestActionBase fromValue(String v) {
        for (TitleRequestActionBase c: TitleRequestActionBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
