//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrustClassificationBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrustClassificationBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="CommunityLandTrust"/>
 *     &lt;enumeration value="IllinoisLandTrust"/>
 *     &lt;enumeration value="LandTrust"/>
 *     &lt;enumeration value="LivingTrust"/>
 *     &lt;enumeration value="NativeAmericanLandTrust"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "TrustClassificationBase")
@XmlEnum
public enum TrustClassificationBase {


    /**
     * A community land trust is a nonprofit corporation that develops and stewards affordable housing, community gardens, civic buildings, commercial spaces and other community assets on behalf of a community.
     *
     */
    @XmlEnumValue("CommunityLandTrust")
    COMMUNITY_LAND_TRUST("CommunityLandTrust"),

    /**
     * An Illinois Land Trust, is a unique legal entity with an overlay of statutory approval and constraints. In an Illinois Land Trust, the trustee holds both legal and equitable title to the real property in accordance with the trust agreement. The beneficiary or beneficiaries of the trust have no legal or equitable interest in the real property, but do have the right of possession, management, and control of the real property, as well as a right to the rents, profits and proceeds therefrom. This type of trust is only recognized in the states of:  Idaho, Iowa, Kansas, Maine, Maryland, Minnesota, Missouri, Nebraska, Nevada, New Jersey, Oklahoma, Rhode Island, South Carolina, Vermont, Washington and West Virginia.
     *
     */
    @XmlEnumValue("IllinoisLandTrust")
    ILLINOIS_LAND_TRUST("IllinoisLandTrust"),

    /**
     * A legal agreement where a trustee is appointed to maintain ownership of real property for the benefit of another party: namely, the beneficiary of the trust.
     *
     */
    @XmlEnumValue("LandTrust")
    LAND_TRUST("LandTrust"),

    /**
     * An agreement where the trustee holds the legal possession of a fund, real property or assets that belong to another person, the beneficiary, created while the person is alive.
     *
     */
    @XmlEnumValue("LivingTrust")
    LIVING_TRUST("LivingTrust"),

    /**
     * The federal government holds legal title but the beneficial interest remains with the Individual Indian or Tribe.
     *
     */
    @XmlEnumValue("NativeAmericanLandTrust")
    NATIVE_AMERICAN_LAND_TRUST("NativeAmericanLandTrust"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    TrustClassificationBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrustClassificationBase fromValue(String v) {
        for (TrustClassificationBase c: TrustClassificationBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
