//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * Information about the appraisal report review performed on the appraisal review parent record.
 *
 * <p>Java class for VALUATION_REVIEW_DETAIL complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VALUATION_REVIEW_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppraisalIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOIdentifier" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewDisagreementDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewExtraordinaryAssumptionsDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewImprovementsCompletedIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewMarketValueChangeCommentDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewOriginalAppraisalEffectiveDate" type="{http://www.mismo.org/residential/2009/schemas}MISMODate" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewOriginalAppraisedValueAccurateIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewOriginalAppraisedValueAmount" type="{http://www.mismo.org/residential/2009/schemas}MISMOAmount" minOccurs="0"/>
 *         &lt;element name="AppraisalReviewValueConclusionCommentDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="PropertyMarketValueDecreasedIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{http://www.mismo.org/residential/2009/schemas}VALUATION_REVIEW_DETAIL_EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.mismo.org/residential/2009/schemas}AttributeExtension"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}MISMOresourceLink"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VALUATION_REVIEW_DETAIL", propOrder = {
    "appraisalIdentifier",
    "appraisalReviewDisagreementDescription",
    "appraisalReviewExtraordinaryAssumptionsDescription",
    "appraisalReviewImprovementsCompletedIndicator",
    "appraisalReviewMarketValueChangeCommentDescription",
    "appraisalReviewOriginalAppraisalEffectiveDate",
    "appraisalReviewOriginalAppraisedValueAccurateIndicator",
    "appraisalReviewOriginalAppraisedValueAmount",
    "appraisalReviewValueConclusionCommentDescription",
    "propertyMarketValueDecreasedIndicator",
    "extension"
})
public class VALUATIONREVIEWDETAIL {

    @XmlElementRef(name = "AppraisalIdentifier", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIdentifier> appraisalIdentifier;
    @XmlElementRef(name = "AppraisalReviewDisagreementDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> appraisalReviewDisagreementDescription;
    @XmlElementRef(name = "AppraisalReviewExtraordinaryAssumptionsDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> appraisalReviewExtraordinaryAssumptionsDescription;
    @XmlElementRef(name = "AppraisalReviewImprovementsCompletedIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> appraisalReviewImprovementsCompletedIndicator;
    @XmlElementRef(name = "AppraisalReviewMarketValueChangeCommentDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> appraisalReviewMarketValueChangeCommentDescription;
    @XmlElementRef(name = "AppraisalReviewOriginalAppraisalEffectiveDate", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMODate> appraisalReviewOriginalAppraisalEffectiveDate;
    @XmlElementRef(name = "AppraisalReviewOriginalAppraisedValueAccurateIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> appraisalReviewOriginalAppraisedValueAccurateIndicator;
    @XmlElementRef(name = "AppraisalReviewOriginalAppraisedValueAmount", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOAmount> appraisalReviewOriginalAppraisedValueAmount;
    @XmlElementRef(name = "AppraisalReviewValueConclusionCommentDescription", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOString> appraisalReviewValueConclusionCommentDescription;
    @XmlElementRef(name = "PropertyMarketValueDecreasedIndicator", namespace = "http://www.mismo.org/residential/2009/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<MISMOIndicator> propertyMarketValueDecreasedIndicator;
    @XmlElement(name = "EXTENSION")
    protected VALUATIONREVIEWDETAILEXTENSION extension;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String label;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the appraisalIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public JAXBElement<MISMOIdentifier> getAppraisalIdentifier() {
        return appraisalIdentifier;
    }

    /**
     * Sets the value of the appraisalIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIdentifier }{@code >}
     *
     */
    public void setAppraisalIdentifier(JAXBElement<MISMOIdentifier> value) {
        this.appraisalIdentifier = value;
    }

    /**
     * Gets the value of the appraisalReviewDisagreementDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getAppraisalReviewDisagreementDescription() {
        return appraisalReviewDisagreementDescription;
    }

    /**
     * Sets the value of the appraisalReviewDisagreementDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setAppraisalReviewDisagreementDescription(JAXBElement<MISMOString> value) {
        this.appraisalReviewDisagreementDescription = value;
    }

    /**
     * Gets the value of the appraisalReviewExtraordinaryAssumptionsDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getAppraisalReviewExtraordinaryAssumptionsDescription() {
        return appraisalReviewExtraordinaryAssumptionsDescription;
    }

    /**
     * Sets the value of the appraisalReviewExtraordinaryAssumptionsDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setAppraisalReviewExtraordinaryAssumptionsDescription(JAXBElement<MISMOString> value) {
        this.appraisalReviewExtraordinaryAssumptionsDescription = value;
    }

    /**
     * Gets the value of the appraisalReviewImprovementsCompletedIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getAppraisalReviewImprovementsCompletedIndicator() {
        return appraisalReviewImprovementsCompletedIndicator;
    }

    /**
     * Sets the value of the appraisalReviewImprovementsCompletedIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setAppraisalReviewImprovementsCompletedIndicator(JAXBElement<MISMOIndicator> value) {
        this.appraisalReviewImprovementsCompletedIndicator = value;
    }

    /**
     * Gets the value of the appraisalReviewMarketValueChangeCommentDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getAppraisalReviewMarketValueChangeCommentDescription() {
        return appraisalReviewMarketValueChangeCommentDescription;
    }

    /**
     * Sets the value of the appraisalReviewMarketValueChangeCommentDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setAppraisalReviewMarketValueChangeCommentDescription(JAXBElement<MISMOString> value) {
        this.appraisalReviewMarketValueChangeCommentDescription = value;
    }

    /**
     * Gets the value of the appraisalReviewOriginalAppraisalEffectiveDate property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public JAXBElement<MISMODate> getAppraisalReviewOriginalAppraisalEffectiveDate() {
        return appraisalReviewOriginalAppraisalEffectiveDate;
    }

    /**
     * Sets the value of the appraisalReviewOriginalAppraisalEffectiveDate property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMODate }{@code >}
     *
     */
    public void setAppraisalReviewOriginalAppraisalEffectiveDate(JAXBElement<MISMODate> value) {
        this.appraisalReviewOriginalAppraisalEffectiveDate = value;
    }

    /**
     * Gets the value of the appraisalReviewOriginalAppraisedValueAccurateIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getAppraisalReviewOriginalAppraisedValueAccurateIndicator() {
        return appraisalReviewOriginalAppraisedValueAccurateIndicator;
    }

    /**
     * Sets the value of the appraisalReviewOriginalAppraisedValueAccurateIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setAppraisalReviewOriginalAppraisedValueAccurateIndicator(JAXBElement<MISMOIndicator> value) {
        this.appraisalReviewOriginalAppraisedValueAccurateIndicator = value;
    }

    /**
     * Gets the value of the appraisalReviewOriginalAppraisedValueAmount property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public JAXBElement<MISMOAmount> getAppraisalReviewOriginalAppraisedValueAmount() {
        return appraisalReviewOriginalAppraisedValueAmount;
    }

    /**
     * Sets the value of the appraisalReviewOriginalAppraisedValueAmount property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOAmount }{@code >}
     *
     */
    public void setAppraisalReviewOriginalAppraisedValueAmount(JAXBElement<MISMOAmount> value) {
        this.appraisalReviewOriginalAppraisedValueAmount = value;
    }

    /**
     * Gets the value of the appraisalReviewValueConclusionCommentDescription property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public JAXBElement<MISMOString> getAppraisalReviewValueConclusionCommentDescription() {
        return appraisalReviewValueConclusionCommentDescription;
    }

    /**
     * Sets the value of the appraisalReviewValueConclusionCommentDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOString }{@code >}
     *
     */
    public void setAppraisalReviewValueConclusionCommentDescription(JAXBElement<MISMOString> value) {
        this.appraisalReviewValueConclusionCommentDescription = value;
    }

    /**
     * Gets the value of the propertyMarketValueDecreasedIndicator property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public JAXBElement<MISMOIndicator> getPropertyMarketValueDecreasedIndicator() {
        return propertyMarketValueDecreasedIndicator;
    }

    /**
     * Sets the value of the propertyMarketValueDecreasedIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MISMOIndicator }{@code >}
     *
     */
    public void setPropertyMarketValueDecreasedIndicator(JAXBElement<MISMOIndicator> value) {
        this.propertyMarketValueDecreasedIndicator = value;
    }

    /**
     * Gets the value of the extension property.
     *
     * @return
     *     possible object is
     *     {@link VALUATIONREVIEWDETAILEXTENSION }
     *
     */
    public VALUATIONREVIEWDETAILEXTENSION getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value
     *     allowed object is
     *     {@link VALUATIONREVIEWDETAILEXTENSION }
     *
     */
    public void setEXTENSION(VALUATIONREVIEWDETAILEXTENSION value) {
        this.extension = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
