//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VendorRelationshipBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VendorRelationshipBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Independent"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Staff"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "VendorRelationshipBase")
@XmlEnum
public enum VendorRelationshipBase {


    /**
     * Implies 1099 relationship.
     *
     */
    @XmlEnumValue("Independent")
    INDEPENDENT("Independent"),
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * Implies w-2.
     *
     */
    @XmlEnumValue("Staff")
    STAFF("Staff");
    private final String value;

    VendorRelationshipBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VendorRelationshipBase fromValue(String v) {
        for (VendorRelationshipBase c: VendorRelationshipBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
