//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.02.11 at 08:03:21 AM EST
//


package com.lh.pos.mismo34;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkoutCommentBase.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WorkoutCommentBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="DeedInLieu"/>
 *     &lt;enumeration value="General"/>
 *     &lt;enumeration value="MIDecision"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "WorkoutCommentBase")
@XmlEnum
public enum WorkoutCommentBase {


    /**
     * A comment or note on the loan record related to the creation of a Deed In Lieu solution to foreclosure.
     *
     */
    @XmlEnumValue("DeedInLieu")
    DEED_IN_LIEU("DeedInLieu"),

    /**
     * A comment or note on the loan record not related to default servicing.
     *
     */
    @XmlEnumValue("General")
    GENERAL("General"),

    /**
     * A comment or note on the loan record related to the the MI company's solution to foreclosure.
     *
     */
    @XmlEnumValue("MIDecision")
    MI_DECISION("MIDecision"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    WorkoutCommentBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkoutCommentBase fromValue(String v) {
        for (WorkoutCommentBase c: WorkoutCommentBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
